### ISSUE TITLE
HTMLCollection is not fully "live"

### ISSUE THREAD

**Issue by lddubeau** [jsdom/jsdom#1517]
### Versions

Node 4.4.5
jsdom 9.2.1 (I've also reproduced it with versions down to the latest in the 6 series)
### Steps to reproduce

Run the following test:

```
var html = '\
<html>\
  <head>\
  </head>\
  <body>\
    <div>\
      <div class="test">1</div>\
      <div class="test">2</div>\
      <div class="test">3</div>\
      <div class="test">4</div>\
    </div>\
    <div>\
      <div class="test2">1</div>\
      <div class="test2">2</div>\
      <div class="test2">3</div>\
      <div class="test2">4</div>\
    </div>\
    <script>\
      setTimeout(function () { \
        var tests = document.getElementsByClassName("test");\
        var test;\
        while ((test = tests.item(0))) {\
          console.log("first test textContent", test.textContent);\
          test.parentNode.removeChild(test);\
        }\
      }, 0);\
      setTimeout(function () { \
        var tests = document.body.getElementsByClassName("test2");\
        var test;\
        while ((test = tests.item(0))) {\
          console.log("second test textContent", test.textContent);\
          test.parentNode.removeChild(test);\
        }\
      }, 0);\
    </script>\
  </body>\
</html>';

var jsdom = require("jsdom");
var path = require("path");

var base_path = "file://" + path.join(__dirname);

var vc = jsdom.createVirtualConsole();
vc.on("log", console.log.bind(console.log));
vc.on("jsdomError", function jsdomError(er) {
    throw er;
});

jsdom.env({
    html: html,
    url: base_path,
    features: {
        ProcessExternalResources: ["script"],
    },
    virtualConsole: vc,
    done: function done(error, w) {
        if (error) {
            throw error;
        }
    },
});
```
### Actual output

```
$ node test.js 
first test textContent 1
first test textContent 2
first test textContent 3
first test textContent 4
second test textContent 1
second test textContent 1
/home/ldd/src/jsdom_issues/jsdom_issue1/test.js:47
    throw er;
    ^

Error: Uncaught [TypeError: Cannot read property 'removeChild' of null]
    at reportException (/home/ldd/src/jsdom_issues/jsdom_issue1/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
    at callback [as _onTimeout] (/home/ldd/src/jsdom_issues/jsdom_issue1/node_modules/jsdom/lib/jsdom/browser/Window.js:430:7)
    at Timer.listOnTimeout (timers.js:92:15)
```
### Expected output

```
$ node test.js 
first test textContent 1
first test textContent 2
first test textContent 3
first test textContent 4
second test textContent 1
second test textContent 2
second test textContent 3
second test textContent 4
```
### Observations
1. The first test in the test code was actually initially done using `(test = tests[0])` which does not work because it does not cause a refresh of the collection but I think this is a known issue.
2. The 2nd test passes if we use instead `var tests = document.getElementsByClassName("test2")` or `var tests = document.body.children[1].getElementsByClassName("test2")`. I suspect the problem is that element version changes are not properly propagated up the tree so the collection fails to refresh.

**Comment by domenic** [comment]
Probably fixed by https://github.com/tmpvar/jsdom/pull/1934, although we should add specific tests to chec, since there is still some caching that could potentially still be buggy.

**Comment by TimothyGu** [comment]
This is indeed fixed after #1934. The script now prints

```
first test textContent 1
first test textContent 2
first test textContent 3
first test textContent 4
second test textContent 1
second test textContent 2
second test textContent 3
second test textContent 4
```

as expected.

**Comment by TimothyGu** [comment]
This is the script I used (using the new API):

```js
const { JSDOM } = require(".");

var html = '\
<html>\
  <head>\
  </head>\
  <body>\
    <div>\
      <div class="test">1</div>\
      <div class="test">2</div>\
      <div class="test">3</div>\
      <div class="test">4</div>\
    </div>\
    <div>\
      <div class="test2">1</div>\
      <div class="test2">2</div>\
      <div class="test2">3</div>\
      <div class="test2">4</div>\
    </div>\
    <script>\
      setTimeout(function () { \
        var tests = document.getElementsByClassName("test");\
        var test;\
        while ((test = tests.item(0))) {\
          console.log("first test textContent", test.textContent);\
          test.parentNode.removeChild(test);\
        }\
      }, 0);\
      setTimeout(function () { \
        var tests = document.body.getElementsByClassName("test2");\
        var test;\
        while ((test = tests.item(0))) {\
          console.log("second test textContent", test.textContent);\
          test.parentNode.removeChild(test);\
        }\
      }, 0);\
    </script>\
  </body>\
</html>';

new JSDOM(html, { runScripts: 'dangerously' });
```
