### ISSUE TITLE
Allow disabling the processing of CSS

### ISSUE THREAD

**Issue by cawa-93** [jsdom/jsdom#2005]
### Basic info:

- **Node.js version:** v8.2.1
- **jsdom version:** ^11.2.0

### Minimal reproduction case
If I try parse html contain
```html
<style type="text/css">
@import url("/css/blok_add.css");
</style>
```
I get the following error:
```
Error: Could not parse CSS @import URL /css/blok_add.css relative to base URL "about:blank"
    at scanForImportRules (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\helpers\stylesheets.js:68:25)
    at exports.evaluateStylesheet (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\helpers\stylesheets.js:33:3)
    at HTMLStyleElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\HTMLStyleElement-impl.js:23:5)
    at HTMLTableDataCellElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:281:15)
    at HTMLTableDataCellElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Element-impl.js:93:11)
    at HTMLTableRowElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:281:15)
    at HTMLTableRowElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Element-impl.js:93:11)
    at HTMLTableSectionElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:281:15)
    at HTMLTableSectionElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Element-impl.js:93:11)
    at HTMLTableElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:281:15)
    at HTMLTableElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Element-impl.js:93:11)
    at HTMLDivElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:281:15)
    at HTMLDivElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Element-impl.js:93:11)
    at HTMLTableDataCellElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:281:15)
    at HTMLTableDataCellElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Element-impl.js:93:11)
    at HTMLTableRowElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:281:15)
    at HTMLTableRowElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Element-impl.js:93:11)
    at HTMLTableSectionElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:281:15)
    at HTMLTableSectionElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Element-impl.js:93:11)
    at HTMLTableElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:281:15)
    at HTMLTableElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Element-impl.js:93:11)
    at HTMLDivElementImpl._attach (D:\Develop\parser\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:281:15)
```
The problem can be solved by specifying the parameter url.
```js
new JSDOM(html, {url: 'http://example.com'})
```
However, I'm wondering if **it's possible to completely disable the processing of CSS**?

**Comment by domenic** [comment]
It's not possible at the moment. You can suppress errors using your own VirtualConsole though.

The correct thing to do is indeed to set a base URL.

**Comment by pawel-dubiel** [comment]
The ability to disable certain parts of jsdom features could help optimize performance. And when scrapping content the CSS processing is certainly not needed.

**Comment by cawa-93** [comment]
@pawel-dubiel, Right. In my case, I'm only interested in httml and manipulation with it. I do not need the processing of the CSS and javascript. I would like to disable all this, to improve the speed of work.

**Comment by pawel-dubiel** [comment]
@cawa-93 I'm just thinking if you don't need to use JS/CSS and you don't need DOM API you may consider using cheerio (which should be a few times faster, or at least it was a few years ago ).

**Comment by domenic** [comment]
Do you have any evidence of a performance increase? With my knowledge of jsdom's architecture, there shouldn't be much, if any, since it's all done lazily.

**Comment by pawel-dubiel** [comment]
@domenic 
8x is a claim from https://github.com/cheeriojs/cheerio

> "Blazingly fast: Cheerio works with a very simple, consistent DOM model. As a result parsing, manipulating, and rendering are incredibly efficient. Preliminary end-to-end benchmarks suggest that cheerio is about 8x faster than JSDOM."

And this old screencast https://vimeo.com/31950192 which at the end compares both jsdom and cheerio performance, but it's 6 years old. 

It would be really interesting to see results from 2017.

But both projects have a different scope.

**Comment by domenic** [comment]
Yes, those Cheerio results are really dishonest, as we've mentioned to their author before. And they certainly have nothing to do with CSS.

**Comment by mikegleasonjr** [comment]
I'm in the camp where `cssom` fails to parse my CSS but I still need to parse the `js`.

**Comment by dontcallmedom** [comment]
I too would like to disable inline CSS parsing - it is mostly a waste of CPU and memory in my various usages of jsdom.

**Comment by domenic** [comment]
https://github.com/tmpvar/jsdom/issues/2005#issuecomment-333922999

**Comment by mikegleasonjr** [comment]
For me is having to write more code to gracefully handle CSS parsing "errors" that is bothering me. Even if my CSS is valid (It is just not supported by JSDOM's parser).

**Comment by dontcallmedom** [comment]
Here is a script which, when run alongs with a downloaded copy of https://www.w3.org/TR/html52/single-page.html takes around 6 seconds less on my machine when `evaluateStylesheet` is commented out in `HTMLStyleElement-impl.js`:
```js
const {JSDOM} = require("jsdom");
console.time("DOM parsing");
JSDOM.fromFile("single-page.html").then(dom => {
  console.timeEnd("DOM parsing");
});
```

**Comment by domenic** [comment]
That's great evidence; thanks!

**Comment by KonradLinkowski** [comment]
Has something changed since January 22th?

**Comment by domenic** [comment]
https://mobile.twitter.com/slicknet/status/782274190451671040

**Comment by minas90** [comment]
We have the same issue. We parse hundreds of pages per minute and I tried to remove css from most of them and parsing time decreased drastically, also we get bunch of `Error: Could not parse CSS`. Please make parsing of the css optional. What's the best way to manually fork and disable css parsing?

**Comment by sdgandhi** [comment]
Fork with stylesheet parsing disabled: https://github.com/dfblue/jsdom

**Comment by JikkuJose** [comment]
Quite surprised this wasn't thought of when implementing it! Processing just raw HTML seems to be a very common case when CSS is just a burden to consider.

**Comment by EtzBetz** [comment]
I would like to see an option to disable CSS processing as well..

**Comment by jeffRTC** [comment]
Just hit the wall. 

@domenic I'm not a communist, but let me ask you one thing. How much do you need to implement this feature?
 
 I can write off a Cheque directly to you.

**Comment by asajadian** [comment]
Does this disabling parsing CSS really that complicated? Processing is CSS really not necessary and actually wasteful for a lot of use cases.
It's been more that 3 years now since this issue has been raised! I wish it was resolved by now ☹

**Comment by eedahl** [comment]
Same boat, I just need the HTML and something CSS-related is failing.

**Comment by kfitzgerald** [comment]
Same – And in my case, jsdom is used as a dependency from other libs, so the option to switch to another dom provider just to disable css parsing is not terribly viable.

**Comment by phgn0** [comment]
For anyone else stumbling here, I created yet another fork with the no-CSS patches ontop of the latest JSDOM version: https://github.com/phgn0/jsdom-no-css.

Just use it as `"jsdom": "phgn0/jsdom-no-css#master",` in your package.json (or fork it).

**Comment by weijarz** [comment]
I currently use this to get around it:

```js
new JSDOM(html.replace(/<style(\s|>).*?<\/style>/gi, ''))
```

**Comment by uuf6429** [comment]
Since there are already at least two forks with this fix, I assume it's not relatively difficult to implement, so what's stopping this from progressing @domenic?

Disclaimer: I've also just encountered this problem and in my use-case, I do not need CSS parsing.

**Comment by rudolfbyker** [comment]
Here's a workaround that uses monkey-patching. I think this is easier than keeping forks around:

```
/**
 * Workaround for https://github.com/jsdom/jsdom/issues/2005
 */
export function disableCssProcessing() {
  const HTMLStyleElementImpl =
    require("jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl").implementation;
  HTMLStyleElementImpl.prototype._updateAStyleBlock = () => {};
}
```

**Comment by qcandag** [comment]
Hello, @rudolfbyker  I'm new at this area can you tell me where should I put the code that you gave and run it ? Thanks.

**Comment by khmyznikov** [comment]
TS version of previous patch:
```
import { implementation } from 'jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js';
implementation.prototype._updateAStyleBlock = () => {};
```

**Comment by attacomsian** [comment]
> I currently use this to get around it:
> 
> ```js
> new JSDOM(html.replace(/<style(\s|>).*?<\/style>/gi, ''))
> ```

It didn't work for me. Instead, I found another [regex](https://stackoverflow.com/a/26553146/692466) that works for both inline styles and scripts.

I now use the following code to remove inline CSS and scripts:

```js
const sanitizeHtml = html => {
  return html?.replace(/<style([\S\s]*?)>([\S\s]*?)<\/style>/gim, '')?.replace(/<script([\S\s]*?)>([\S\s]*?)<\/script>/gim, '')
}

let doc = new JSDOM(sanitizeHtml(html), { url })
```

**Comment by thescientist13** [comment]
Just ran into the same issue [as above](https://github.com/jsdom/jsdom/issues/2005#issuecomment-1821748091) regarding CSS nesting support, but was able to apply the [`HTMLStyleElement` patch override](https://github.com/jsdom/jsdom/issues/2005#issuecomment-1496469115).

**Comment by domenic** [comment]
I'm going to close this feature request as wontfix.

I implemented a version of this in https://github.com/jsdom/jsdom/pull/3861. However, I found that there were no performance benefits (within the statistical margin of error). Certainly nothing like the multi-second speedups claimed by @dontcallmedom in https://github.com/jsdom/jsdom/issues/2005#issuecomment-359532781.

@dontcallmedom's original reproduction case now redirects to the HTML Standard, which has no `<style>` elements. I tried using a [DOM Standard snapshot](https://dom.spec.whatwg.org/commit-snapshots/eaf2ac7044cb2711024965486a3f0d76631c5611/) instead as an example of a relatively-large document with a number of inline styles. (Probably a similar amount to the HTML 5.2 fork, since both are generated by the Bikeshed software.) But I got no difference.

If people can provide an example page where this makes a difference, I'll consider reopening this and resurrecting https://github.com/jsdom/jsdom/pull/3861.

Some things to note:

- Some time might be saved by simply not fetching external `<link>` stylesheets. The appropriate tool for avoiding that is to [customize the jsdom resource loader](https://github.com/jsdom/jsdom/?tab=readme-ov-file#loading-subresources). Adding a separate disable-CSS option is not something we want to add on top of that existing customizability.

- The semantics of `disableCSS`, as you can see from [the tests in the closed PR](https://github.com/jsdom/jsdom/blob/6f610b6b1aa1c50ac7dc413bdb16569a2535b317/test/api/options-disable-css.js), are not trivial. I decided to have `styleElement.sheet` and `linkElement.sheet` return `null`, but have `element.style` and `window.getComputedStyle()` return dummy objects that have mostly empty string properties. Removing the synchronization between `element.style` and `element.getAttribute("style")` is especially strange. I'm not really sure what the best choice would be for such a "CSS disabled" mode---e.g., maybe `window.getComputedStyle()` and `element.style` should not exist instead? This is just another reason why I'm hesitant about adding this functionality unless it gives really large benefits.

- The majority of people in this thread seem to be complaining about CSS parsing console messages due to jsdom's subpar CSS support. The appropriate tool for suppressing console messages is jsdom's [virtual console API](https://github.com/jsdom/jsdom/?tab=readme-ov-file#virtual-consoles). We have an issue open tracking better documentation for that, and making it easier to filter out types of console messages that you don't care about, in https://github.com/jsdom/jsdom/issues/3596. But in the meantime it's perfectly possible to just filter them out yourselves with a bit of custom code. We don't need to add a new feature for that.

**Comment by TonyGravagno** [comment]
For anyone following breadcrumbs here from the interwebs, a console.error is still called by JSDOM even if there is a 'url' value in options. Now go to the virtual console API info.

**Comment by t1rnrny** [comment]
I mean it doesnt seem to affect scraping the data you need but the error message is annoying, why is it not planned when css is not needed for the vast majority of uses of jsdom

**Comment by domenic** [comment]
Please see https://github.com/jsdom/jsdom?tab=readme-ov-file#virtual-consoles if you would like to change what error messages are output. As for your claim that "css is not needed for the vast majority of uses of jsdom", that seems almost certainly false, [judging from our issue tracker](https://github.com/jsdom/jsdom/issues?q=is%3Aissue%20state%3Aopen%20label%3Acss).

**Comment by Gaelan** [comment]
For anyone else investigating a similar issue: our test suite was spending about half its time parsing CSS. This was because styled-components (we're using v5, but I think v6 is the same) has O(n^2) behavior in its default configuration when `NODE_ENV != "production"`: each unique component appends some styles to a shared `<style>` tag when it first renders, and jsdom parses the full contents of the `<style>` tag each time.

There was a simple fix, at least: styled-components has a "speedy mode" which uses [CSSOM](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model) instead of manipulating text in a `<style>` tag. This is orders of magnitude faster. Speedy mode is only enabled for production builds by default, but can be enabled elsewhere by setting `SC_DISABLE_SPEEDY=false`, or in a [few other ways](https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/constants.ts).
