### ISSUE TITLE
Could not parse CSS Stylesheet, when inline style tag font-family has space

### ISSUE THREAD

**Issue by AlbinoDrought** [jsdom/jsdom#2123]
~~At first I was blaming this on CSSOM, but after some digging it seems like the `content` passed to CSSOM [here](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/nodes/HTMLStyleElement-impl.js#L20) is not complete.~~ (seems to be how the parser works)

### Basic info:

- **Node.js version:** v9.2.1
- **jsdom version:** 11.6.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM(`
<html>
  <head></head>
  <body>
    <style>
    .cool-class {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }
    </style>
    <p class="cool-class">
    Hello!
    </p>
  </body>
</html>
`);
```

### Output:

```
Error: Could not parse CSS stylesheet
    at exports.evaluateStylesheet (jsdom/lib/jsdom/living/helpers/stylesheets.js:23:21)
    at HTMLStyleElementImpl._childTextContentChangeSteps (jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:20:5)
    at TextImpl.replaceData (jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:73:23)
    at TextImpl.set data [as data] (jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:21:10)
    at JSDOMParse5Adapter.insertText (jsdom/lib/jsdom/browser/parse5-adapter-parsing.js:115:22)
    at module.exports.Parser._insertCharacters (parse5/lib/parser/index.js:558:26)
    at Object.insertCharacters (parse5/lib/parser/index.js:1014:7)
    at module.exports.Parser._processToken (parse5/lib/parser/index.js:607:38)
    at module.exports.Parser._processInputToken (parse5/lib/parser/index.js:639:14)
    at module.exports.Parser._runParsingLoop (parse5/lib/parser/index.js:409:14) 
    .cool-class {
        font-family: "Helvetica
Error: Could not parse CSS stylesheet
    at exports.evaluateStylesheet (jsdom/lib/jsdom/living/helpers/stylesheets.js:23:21)
    at HTMLStyleElementImpl._childTextContentChangeSteps (jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:20:5)
    at TextImpl.replaceData (jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:73:23)
    at TextImpl.set data [as data] (jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:21:10)
    at JSDOMParse5Adapter.insertText (jsdom/lib/jsdom/browser/parse5-adapter-parsing.js:115:22)
    at module.exports.Parser._insertCharacters (parse5/lib/parser/index.js:558:26)
    at Object.insertCharacters (parse5/lib/parser/index.js:1014:7)
    at module.exports.Parser._processToken (parse5/lib/parser/index.js:607:38)
    at module.exports.Parser._processInputToken (parse5/lib/parser/index.js:639:14)
    at module.exports.Parser._runParsingLoop (parse5/lib/parser/index.js:409:14) 
    .cool-class {
        font-family: "Helvetica 
```

### How does similar code behave in browsers?

The HTML works fine in browsers, and sets the font properly: https://jsfiddle.net/tveprk11/

---

Removing the space from `"Helvetica Neue"` allows the code to run without errors.

**Comment by domenic** [comment]
This probably regressed in 11.6.0 due to our parsing changes. IIRC parse5 feeds us new text nodes if there is a space. We probably need to do something similar to what we do for script elements.

I'll try to fix/hack around soon.
