### ISSUE TITLE
Error: Could not parse CSS stylesheet with jsdom 11.6.0

### ISSUE THREAD

**Issue by foolip** [jsdom/jsdom#2131]
### Basic info:

- **Node.js version:** 8.5.0 (used to find regression range), 9.4.0 used where first detected
- **jsdom version:** 11.6.0 (local testing, on Travis I think it was 11.6.1)

### Minimal reproduction case

```js
'use strict'

const fetch = require('node-fetch'); // 1.7.3
const JSDOM = require('jsdom').JSDOM

async function repro(url) {
  const response = await fetch(url);
  const text = await response.text();
  const document = new JSDOM(text).window.document;
  console.log(document);
  return document;
}

repro('https://web.archive.org/web/20180127184316/https://w3c.github.io/webauthn/')

```

The errors are very verbose, starting with:
```
Error: Could not parse CSS stylesheet
    at exports.evaluateStylesheet (/Users/foolip/src/day-to-day/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:23:21)
    at HTMLStyleElementImpl._childTextContentChangeSteps (/Users/foolip/src/day-to-day/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:20:5)
    at HTMLStyleElementImpl.insertBefore (/Users/foolip/src/day-to-day/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:225:14)
    at HTMLStyleElementImpl.appendChild (/Users/foolip/src/day-to-day/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:327:17)
    at JSDOMParse5Adapter.insertText (/Users/foolip/src/day-to-day/node_modules/jsdom/lib/jsdom/browser/parse5-adapter-parsing.js:119:18)
    at module.exports.Parser._insertCharacters (/Users/foolip/src/day-to-day/node_modules/parse5/lib/parser/index.js:558:26)
    at Object.insertCharacters (/Users/foolip/src/day-to-day/node_modules/parse5/lib/parser/index.js:1014:7)
    at module.exports.Parser._processToken (/Users/foolip/src/day-to-day/node_modules/parse5/lib/parser/index.js:607:38)
    at module.exports.Parser._processInputToken (/Users/foolip/src/day-to-day/node_modules/parse5/lib/parser/index.js:639:14)
    at module.exports.Parser._runParsingLoop (/Users/foolip/src/day-to-day/node_modules/parse5/lib/parser/index.js:409:14) /*
```

https://travis-ci.org/foolip/day-to-day/builds/331681172 is where I first saw it.

https://travis-ci.org/foolip/day-to-day/builds/334160581 is where I "fixed" it by locking to jsdom 11.5.1.

**Comment by foolip** [comment]
Probably a similar cause to https://github.com/jsdom/jsdom/issues/2123, certainly 8c84ebf3b7f3420b6e6cc68612ed3e0b9c1f4455 is what I suspected when looking at the changes. Don't know how to lock to a commit to confirm though.

**Comment by foolip** [comment]
Confirmed fixed: https://travis-ci.org/foolip/day-to-day/builds/335059452

Thanks @domenic!

**Comment by aphofstede** [comment]
I'm getting this after upgrading from 11.5.1 to 11.6.2 on the sweetalert2 CSS, when mounting a Vue component during a vue-test-utils test run. (which uses JSDOM) @domenic How do I ascertain if JSDOM is to blame or not?

```
Error: Could not parse CSS stylesheet
    at exports.createStylesheet (node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:35:21)
    at HTMLStyleElementImpl._updateAStyleBlock (node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:68:5)
    at HTMLStyleElementImpl._childTextContentChangeSteps (node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:37:12)
    at HTMLStyleElementImpl.insertBefore (node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:225:14)
    at HTMLStyleElementImpl.appendChild (node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:327:17)
    at HTMLStyleElement.appendChild (node_modules/jsdom/lib/jsdom/living/generated/Node.js:192:45)
    at injectCSS (.tmp/mocha-webpack/1521302543988/webpack:/node_modules/sweetalert2/dist/sweetalert2.all.js:1796:1) 
[snip]
