### ISSUE TITLE
canvas.toBlob never reached

### ISSUE THREAD

**Issue by jacktuck** [jsdom/jsdom#2137]
### Basic info:

- **Node.js version:** 
v8.4.0
- **jsdom version:** 
v9

v9 because need to load remote resources

### Minimal reproduction case

```js
const jsdom = require('jsdom')
const Canvas = require('canvas-prebuilt')
const pify = require('pify')
const config = require('./config')

const eval = pify(jsdom.env)

jsdom.defaultDocumentFeatures = {
  FetchExternalResources: ['script'],
  ProcessExternalResources: true
}

;(async function (exports) {
  const chart = 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.js'

  const html = `<html>
    <body>
      <div id="chart-div" style="font-size:12; width:400; height:400;">
        <canvas id="myChart" width="400" height="400"></canvas>
      </div>
    </body>

  </html>`

  try {
    const window = await eval(html, [chart])

    window._canvas = window.document.getElementById('myChart')
    window.ctx = window._canvas.getContext('2d')

    window.config = config

    window.CanvasRenderingContext2D = Canvas.Context2d

    window.Chart(window.ctx, window.config)

    window._chart = new window.Chart(window.ctx, window.config)

    window._canvas.toBlob(function (blob, err) { // no error
      console.log('BLOB', blob) // never reached
    }, 'image/png')

    window._canvas.toBlob(function (blob, err) { // Empty JPEG image (DNL not supported)
      console.log('BLOB', blob) // never reached
    }, 'image/jpg')
  } catch (e) {
    console.log('ERR', e)
  }
})(module.exports)
```

Code is also on gh https://github.com/jacktuck/node-chartjs

**Comment by jacktuck** [comment]
Hmm.

Now i get
```TypeError: Cannot read property 'length' of null
    at acquireContext (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.js:3937:18)
    at new Chart.Controller (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.js:3990:17)
    at new Chart (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.js:6386:21)
    at /Users/jt/dev/node-chartjs/index.js:37:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)```

**Comment by domenic** [comment]
The newest version also supports loading remote resources; see the documentation. Can you edit your example to use that? It's not generally a great use of our time to debug code that might have been fixed years ago.

Please also remove the pify dependency, as having to debug third-party dependencies is outside our scope.

**Comment by jacktuck** [comment]
@domenic I tried to find documentation for loading remotes on the newest version. But will close for now then.
