### ISSUE TITLE
WebSocket throws error on close before connected, should silently close

### ISSUE THREAD

**Issue by reem** [jsdom/jsdom#2153]
WebSocket implementation unnecessarily (and inconveniently) throws errors when closing a WebSocket before it has connected. The correct behavior would be to simply silently close the socket/cancel connecting.

Relevant logic:

https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/websockets/WebSocket-impl.js#L260-L271

### Basic info:

- **Node.js version:** v8
- **jsdom version:** 11.6.2

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM(`
  <!doctype html><html><body></body></html>
`);

const ws = new dom.window.WebSocket('wss://echo.websocket.org/');
ws.close(); // error occurs internally
```
Sample error:

```
Error: Uncaught [Error: Unhandled "error" event. ([object Event])]
    at reportException (/Users/reem/code/project/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at invokeEventListeners (/Users/reem/code/project/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
    at WebSocketImpl._dispatch (/Users/reem/code/project/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at WebSocketImpl._onConnectionClosed (/Users/reem/code/project/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:222:12)
    at WebSocket._ws.once.args (/Users/reem/code/project/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:136:14)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at WebSocket.emitClose (/Users/reem/code/project/node_modules/jsdom/node_modules/ws/lib/websocket.js:219:10)
    at WebSocket.finalize (/Users/reem/code/project/node_modules/jsdom/node_modules/ws/lib/websocket.js:191:36)
    at WebSocket.terminate (/Users/reem/code/project/node_modules/jsdom/node_modules/ws/lib/websocket.js:405:12)
    at WebSocketImpl._close (/Users/reem/code/project/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:264:18)
    at WebSocketImpl.close (/Users/reem/code/project/node_modules/jsdom/lib/jsdom/living/websockets/WebSocket-impl.js:257:10)
    at WebSocket.close (/Users/reem/code/project/node_modules/jsdom/lib/jsdom/living/generated/WebSocket.js:102:25)
```

### How does similar code behave in browsers?

Does not error.

**Comment by TimothyGu** [comment]
This isn’t actually a thrown error, but a message printed to the console. You can control if you want to print this by using your own virtual console with `"jsdomError"` event handler. See https://github.com/jsdom/jsdom/blob/master/README.md#virtual-consoles
