### ISSUE TITLE
'Error: Could not parse CSS stylesheet' since 11.6.x

### ISSUE THREAD

**Issue by aphofstede** [jsdom/jsdom#2177]
### Basic info:

- **Node.js version:** 8.9.1
- **jsdom version:** 11.6.2

I'm getting this error after upgrading from 11.5.1 to 11.6.2 on the sweetalert2 CSS, when mounting a Vue component during a vue-test-utils mocha-webpack test run. (which uses JSDOM) 
Let me know if I can supply more details; not sure how to debug this.

```
Error: Could not parse CSS stylesheet
    at exports.createStylesheet (node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:35:21)
    at HTMLStyleElementImpl._updateAStyleBlock (node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:68:5)
    at HTMLStyleElementImpl._childTextContentChangeSteps (node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:37:12)
    at HTMLStyleElementImpl.insertBefore (node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:225:14)
    at HTMLStyleElementImpl.insertBefore (node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:202:14)
    at HTMLStyleElementImpl.appendChild (node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:327:17)
    at HTMLToDOM._parseWithParse5 (node_modules/jsdom/lib/jsdom/browser/htmltodom.js:60:21)
    at HTMLToDOM._doParse (node_modules/jsdom/lib/jsdom/browser/htmltodom.js:47:42)
    at HTMLToDOM.appendToNode (node_modules/jsdom/lib/jsdom/browser/htmltodom.js:37:17)
    at setInnerHTML (node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:40:25)
    at HTMLStyleElementImpl.set innerHTML [as innerHTML] (node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:211:5)
    at HTMLStyleElement.set [as innerHTML] (node_modules/jsdom/lib/jsdom/living/generated/Element.js:874:29)
    at node_modules/sweetalert2/dist/sweetalert2.all.js:1978:1
    at Object.<anonymous> (node_modules/sweetalert2/dist/sweetalert2.all.js:1978:1)
[snip]
```

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
    runScripts: "dangerously",
    resources: "usable"
};
const dom = new JSDOM(`
<html>
    <head>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.18.0/sweetalert2.css" rel="stylesheet" type="text/css" media="all">
    </head>
</html>
`, options);
```

**Comment by domenic** [comment]
Unfortunately this does not follow the issue template, so we cannot help. Feel free to edit the OP to do so, then leave a comment, and we can reopen.

**Comment by aphofstede** [comment]
@domenic Updated

**Comment by domenic** [comment]
Perfect, thanks!

**Comment by domenic** [comment]
Unfortunately it looks like this is due to the stylesheet using (legitimate) features that our CSS parser does not support. Given jsdom's current parser, this results in us throwing out the entire stylesheet, and giving you a warning in the console.

There's not much you can do here. If you find this message unsightly, you can suppress it (and other similar messages) using the techniques at https://github.com/jsdom/jsdom#virtual-consoles (this is a `"jsdomError"`). The long-term fix is for us to get a better CSS parser, but that's quite difficult.

**Comment by aphofstede** [comment]
As an intermediate solution maybe investigate how to make the message more expressive? (Only print the CSS that couldn't be parsed?) In that way one would be more inclined to look in to adding support for that specific CSS feature. At the moment I have no idea what's causing it.
Unless you'll be switching to a third-party CSS parser and don't want to build this one out..

**Comment by domenic** [comment]
We don't really get that information from our CSS parser, unfortunately :(. And our CSS parser isn't really well-maintained so it isn't easy to add support for features to it :(. @Zirro had a project to completely replace it in https://github.com/Zirro/css-object-model but it never quite got finished...

**Comment by domenic** [comment]
I don't know anything about ava, sorry.

**Comment by jktravis** [comment]
@aphofstede Did you work around the issue somehow? I have the same problem, and seemingly with the same library. I'm using Jest, though, and not sure how to handle this in that case.

**Comment by aphofstede** [comment]
@jktravis :)
```// Prevent a lot of "[vuex] unknown mutation type .." logs during tests
const _ = require('lodash')
const originalConsoleError = console.error
console.error = function(msg) {
  if(_.startsWith(msg, '[vuex] unknown')) return
  if(_.startsWith(msg, 'Error: Could not parse CSS stylesheet')) return
  originalConsoleError(msg)
}
```

**Comment by CentralForce** [comment]
I also ran into this problem the other day.
In my case i'm not doing anything with css properties.
So I was wondering if there is a way to disable the css parsing?

**Comment by bluelovers** [comment]
i use VirtualConsole , but this error still happen

and in my env , i have some reason, so i don't use https://github.com/jsdom/jsdom/issues/2177#issuecomment-426825829

hope a options for ignore this error

```ts
const jsdom = await JSDOM.fromURL(`http://127.0.0.1:${rootOptions.server.port}${route}`, {
							resources: 'usable',
							runScripts: 'dangerously',
							// @ts-ignore
							pretendToBeVisual: true,
							includeNodeLocations: true,

							referrer,

							VirtualConsole: virtualConsole,
						});
```

```
2:59:38 PM: Error: Could not parse CSS stylesheet
2:59:38 PM:     at Object.exports.createStylesheet (/opt/build/repo/node_modules/prerenderer-renderer-jsdom/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:34:21)
2:59:38 PM:     at onStylesheetLoad (/opt/build/repo/node_modules/prerenderer-renderer-jsdom/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:74:13)
2:59:38 PM:     at onLoadWrapped (/opt/build/repo/node_modules/prerenderer-renderer-jsdom/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:53:33)
2:59:38 PM:     at Object.check (/opt/build/repo/node_modules/prerenderer-renderer-jsdom/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:76:23)
2:59:38 PM:     at /opt/build/repo/node_modules/prerenderer-renderer-jsdom/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:119:14
2:59:38 PM:     at processTicksAndRejections (internal/process/task_queues.js:89:5) @import url(https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c);@import url(https://fonts.googleapis.com/css?family=Audiowide);@-moz-keyframes shake{59%{margin-left:0}60%,80%{margin-left:2px}70%,90%{margin-left:-2px}}@-webkit-keyframes shake{59%{margin-left:0}60%,80%{margin-left:2px}70%,90%{margin-left:-2px}}@-o-keyframes shake{59%{margin-left:0}60%,80%{margin-left:2px}70%,90%{margin-left:-2px}}@keyframes shake{59%{margin-left:0}60%,80%{margin-left:2px}70%,90%{margin-left:-2px}}.black{background-color:#000!important;border-color:#000!important}.black--text{color:#000!important;caret-color:#000!important}.white{background-color:#fff!important;border-color:#fff!important}.white--text{color:#fff!important;caret-color:#fff!important}.transparent{background-color:transparent!important;border-color:transparent!important}.transparent--text{color:transparent!important;caret-color:transparent!important}.red{background-color:#f44336!important;border-color:#f44336!important}.red--text{color:#f44336!important;caret-color:#f44336!important}.red.lighten-5{background-color:#ffebee!important;border-color:#ffebee!important}.red--text.text--lighten-5{color:#ffebee!important;caret-color:#ffebee!important}.red.lighten-4{background-
```

**Comment by joetidee** [comment]
Getting same issue here too - still no resolution?

**Comment by faroukfaiz10** [comment]
This workaround works for me.
```
const virtualConsole = new jsdom.VirtualConsole();
virtualConsole.sendTo(console, { omitJSDOMErrors: true });
virtualConsole.on("jsdomError", (err) => {
    if (err.message !== "Could not parse CSS stylesheet") {
        console.error(err);
    }
});
```

**Comment by cmacdonnacha** [comment]
I've added this workaround to my `setupTests.ts` file which runs before every test run:

```
beforeAll(() => {
  const originalWarn = console.warn.bind(console.warn);
  console.warn = (msg) => !msg.toString().includes('CSSOM') && originalWarn(msg);
});
```

**Comment by posti85** [comment]
My solution, based on @aphofstede workaround, considering that `console.error` could have many params, and some of them might not be strings:
```
const originalConsoleError = console.error;
const jsDomCssError = 'Error: Could not parse CSS stylesheet';
console.error = (...params) => {
  if (!params.find(p => p.toString().includes(jsDomCssError))) {
    originalConsoleError(...params);
  }
};
```

**Comment by Forest-Gio** [comment]
this is not fixing the error just a work around no? is there a fix for the error instead of suppressing it?

**Comment by Trolejbus** [comment]
I also met this issue when trying to use Jest in newest Angular project. One of Angular most common UI library called PrimeNg has added @layer at-rule into their stylesheets. And it started to throw in Jest unit tests:

`console.error
      Error: Could not parse CSS stylesheet
          at exports.createStylesheet (C:\sources\creditboard-new\CreditBoard\ClientApp\node_modules\jsdom\lib\jsdom\living\helpers\stylesheets.js:34:21)
...
detail: '@layer primeng{p-inputnumber,.p-inputnumber{display:inline-flex}...
`

So far workaround with console.error replacement is working.

**Comment by dcb99** [comment]
I am also receiving similar error when running unit tests with Vite/Vitest

**Comment by davidglezz** [comment]
Any news?
I think this is enough to check the error and it is faster:
```ts
const originalConsoleError = console.error;
console.error = (...args) => {
  if (args?.[0]?.type !== "css parsing") {
    originalConsoleError(...args);
  }
};
```

**Comment by satyavh** [comment]
Use `happy-dom` instead, it can parse modern css unlike jsdom

**Comment by JordanDDisch** [comment]
> Use `happy-dom` instead, it can parse modern css unlike jsdom

This does remove the css parsing errors. Not sure what the consequences are though. But i'm running tests using vitest and rendering react components and works fine with the single test file that i'm working on atm.

**Comment by helgetan** [comment]
still having the issue, any updates here?

**Comment by Exac** [comment]
So https://github.com/jsdom/jsdom/pull/3811 is merged now, does that fix this?
