### ISSUE TITLE
SyntaxError thrown by querySelector when selector contains apostrophe

### ISSUE THREAD

**Issue by davidar** [jsdom/jsdom#2204]
### Basic info:

- **Node.js version:** 9.11.0 
- **jsdom version:** 11.8.0 

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM(`<!DOCTYPE html><p>Hello <a href="#" onclick="window.open('http://example.com/')">world</a></p>`);

console.log(dom.window.document.querySelector(`a[onclick^="window.open('http://"]`).textContent);

console.log(dom.window.document.querySelector(`a[onclick^="window.open("]`).textContent)
// prints "world"

console.log(dom.window.document.querySelector(`a[onclick^="window.open('"]`).textContent)
// SyntaxError: Invalid or unexpected token
//     at DocumentImpl.<anonymous> (.../node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:70:11)
//     at DocumentImpl.querySelector (.../node_modules/jsdom/lib/jsdom/utils.js:123:45)
//     at Document.querySelector (.../node_modules/jsdom/lib/jsdom/living/generated/Document.js:689:45)
```

### How does similar code behave in browsers?

https://jsbin.com/nokegupeye/edit?js,console

**Comment by domenic** [comment]
This may also get fixed by #2187. /cc @Zirro @dperini
