### ISSUE TITLE
Unwanted console output when setting outerHTML property of a node

### ISSUE THREAD

**Issue by genemars** [jsdom/jsdom#2280]
JSDOM outputs non-existent error and the whole text of failing `style` element when set via `outerHTML` property.
Is there a way to prevent this output?
```
Error: Could not parse CSS stylesheet
    at exports.createStylesheet (/home/gene/WebstormProjects/zuix/zuix-website/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:35:21)
    at HTMLStyleElementImpl._updateAStyleBlock (/home/gene/WebstormProjects/zuix/zuix-website/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:67:5)
    at HTMLStyleElementImpl._attach (/home/gene/WebstormProjects/zuix/zuix-website/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:19:12)
    at HTMLHeadElementImpl.insertBefore (/home/gene/WebstormProjects/zuix/zuix-website/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:218:22)
    at HTMLHeadElementImpl.insertBefore (/home/gene/WebstormProjects/zuix/zuix-website/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:191:14)
    at HTMLHeadElementImpl.appendChild (/home/gene/WebstormProjects/zuix/zuix-website/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:316:17)
    at HTMLToDOM._parseWithParse5 (/home/gene/WebstormProjects/zuix/zuix-website/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:61:21)
    at HTMLToDOM._doParse (/home/gene/WebstormProjects/zuix/zuix-website/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:48:42)
    at HTMLToDOM.appendToNode (/home/gene/WebstormProjects/zuix/zuix-website/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:38:17)
    at setInnerHTML (/home/gene/WebstormProjects/zuix/zuix-website/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:41:25) 

[omitted very long output of text passed to `el.outerHTML` prop]
```

### Basic info:

- **Node.js version:** 8.1.0
- **jsdom version:** 11.10.0

### Minimal reproduction case

```js
const request = require('sync-request');
const jsdom = require('jsdom');
const {JSDOM} = jsdom;
const dom = new JSDOM('<html><head><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.3.0/material.min.css" /></head><body></body></html>');
const styleList = dom.window.document.querySelectorAll('link[href]');
if (styleList != null) {
    styleList.forEach(function(el) {
        const res = request('GET', el.getAttribute('href'));
        if (res.statusCode === 200) {
            const content = res.getBody('utf8');
            el.outerHTML = '<style>\n/*{% raw %}*/\n'+content+'\n/*{% endraw %}*/\n</style>';
        }
    });
}
```

### How does similar code behave in browsers?

n.a.

**Comment by domenic** [comment]
Use https://github.com/jsdom/jsdom?tab=readme-ov-file#virtual-consoles to filter console output.
