### ISSUE TITLE
TypeError: The super constructor to "inherits" must not be null or undefined

### ISSUE THREAD

**Issue by bulldetektor** [jsdom/jsdom#2293]
### Basic info:

- **Node.js version:** 8.11.3
- **jsdom version:** 11.11.0

### Minimal reproduction case

```ts
import { JSDOM } from "jsdom";
const dom = new JSDOM("<!doctype html><html><body></body></html>");
// tslint:disable-next-line:no-string-literal
global["document"] = dom.window.document;
// tslint:disable-next-line:no-string-literal
global["window"] = dom.window;
```

### How does similar code behave in browsers?
N/A as I'm trying to run some tests using Mocha

The error I'm getting is this;

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.inherits (util.js:939:11)
    at Object.<anonymous> (C:\[dir]\node_modules\tunnel-agent\index.js:71:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\[dir]\node_modules\request\lib\tunnel.js:4:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\[dir]\node_modules\request\request.js:29:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\[dir]\node_modules\request\index.js:143:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at C:\[dir]\node_modules\request-promise-native\lib\rp.js:8:12
    at module.exports (C:\[dir]\node_modules\stealthy-require\lib\index.js:62:23)
    at Object.<anonymous> (C:\[dir]\node_modules\request-promise-native\lib\rp.js:7:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\[dir]\node_modules\jsdom\lib\api.js:6:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    ....

Seems to be a problem in the tunnel-agent dependency, but I've looked at the code that errors and I can't see why it's complaining. Maybe someone with more node experience might spot the problem? Here's the code that it complains about;

```
function TunnelingAgent(options) {
  var self = this
  self.options = options || {}
  self.proxyOptions = self.options.proxy || {}
  self.maxSockets = self.options.maxSockets || http.Agent.defaultMaxSockets
  self.requests = []
  self.sockets = []

  self.on('free', function onFree(socket, host, port) {
    for (var i = 0, len = self.requests.length; i < len; ++i) {
      var pending = self.requests[i]
      if (pending.host === host && pending.port === port) {
        // Detect the request to connect same origin server,
        // reuse the connection.
        self.requests.splice(i, 1)
        pending.request.onSocket(socket)
        return
      }
    }
    socket.destroy()
    self.removeSocket(socket)
  })
}
util.inherits(TunnelingAgent, events.EventEmitter)
```
It's the last line here that generates the error and the 'events' is imported like this;

`events = require('events')`

... which as far as I can tell is correct.

**Comment by TimothyGu** [comment]
https://github.com/jsdom/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global

Also, you did not create a minimal reproduction case. First, I cannot execute the following code on Node.js because of the `import` statement, and second if I were to change `import` to `require()` the code does not throw any error.

Unfortunately, we cannot debug your dependencies for you.

```js
import { JSDOM } from "jsdom";
const dom = new JSDOM("<!doctype html><html><body></body></html>");
// tslint:disable-next-line:no-string-literal
global["document"] = dom.window.document;
// tslint:disable-next-line:no-string-literal
global["window"] = dom.window;
```
