### ISSUE TITLE
Error: Cross origin null forbidden (Vue, Mocha, Axios)

### ISSUE THREAD

**Issue by andreshg112** [jsdom/jsdom#2319]
### Basic info:

- **Node.js version:** 9.11.2
- **jsdom version:** 11.12.0

### Minimal reproduction case

```js
import chai from "chai";
chai.should();
chai.use(require("chai-json-schema"));
chai.use(require("chai-things"));
chai.config.includeStack = true;
const { assert } = chai;

import { deletedSchema } from "./schemas";

import { deleteState } from "@/utils/api";

it("deleteState", async () => {
  const id = 8;
  const result = await deleteState(id);
  console.log("result: ", result);
  assert.jsonSchema(result.data, deletedSchema);
});

export function deleteState(id) {
  return axios.delete(`${STATES_URL}/${id}`);
}
```

`deleteState()` works fine in the browser.

```console
Error: Cross origin null forbidden
    at dispatchError (/home/andreshg112/Projects/Vue/issues-frontend/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:65:19)
    at Object.validCORSHeaders (/home/andreshg112/Projects/Vue/issues-frontend/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:77:5)
    at receiveResponse (/home/andreshg112/Projects/Vue/issues-frontend/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:847:21)    at EventEmitter.client.on.res (/home/andreshg112/Projects/Vue/issues-frontend/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:679:38)
    at EventEmitter.emit (events.js:180:13)
    at Request.realClient.on.res (/home/andreshg112/Projects/Vue/issues-frontend/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:393:16)
    at Request.emit (events.js:180:13)
    at Request.onRequestResponse (/home/andreshg112/Projects/Vue/issues-frontend/node_modules/request/request.js:1062:10)
    at ClientRequest.emit (events.js:180:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:540:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:445:20)
    at TLSSocket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at TLSSocket.Readable.push (_stream_readable.js:218:10)
    at TLSWrap.onread (net.js:581:20) undefined
  1) deleteState

  0 passing (5s)
  1 failing

  1) deleteState:
     Error: Network Error
      at createError (dist/webpack:/node_modules/axios/lib/core/createError.js:16:1)
      at XMLHttpRequest.handleError (dist/webpack:/node_modules/axios/lib/adapters/xhr.js:87:1)
      at XMLHttpRequest.el.addEventListener.event (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at XMLHttpRequestEventTargetImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at XMLHttpRequestEventTargetImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at XMLHttpRequest.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at requestErrorSteps (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:132:7)
      at dispatchError (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:62:3)
      at Object.validCORSHeaders (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:77:5)
      at receiveResponse (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:847:21)
      at EventEmitter.client.on.res (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:679:38)
      at Request.realClient.on.res (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:393:16)
      at Request.onRequestResponse (node_modules/request/request.js:1062:10)
      at HTTPParser.parserOnIncomingClient (_http_client.js:540:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
      at TLSSocket.socketOnData (_http_client.js:445:20)
      at addChunk (_stream_readable.js:274:12)
      at readableAddChunk (_stream_readable.js:261:11)
      at TLSSocket.Readable.push (_stream_readable.js:218:10)
      at TLSWrap.onread (net.js:581:20)



 MOCHA  Tests completed with 1 failure(s)

 ERROR  mocha-webpack exited with code 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! issues-frontend@0.1.0 test:unit: `vue-cli-service test:unit -t 0 "tests/unit/utils/temp.spec.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the issues-frontend@0.1.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/andreshg112/.npm/_logs/2018-08-03T16_47_46_272Z-debug.log
```

**Comment by TimothyGu** [comment]
The bug report does not follow our https://github.com/jsdom/jsdom/blob/master/.github/ISSUE_TEMPLATE.md. In particular, your minimal reproduction case does not have `jsdom` anywhere.

When you make it conform to that style we'll able to debug and reopen this issue.

**Comment by andreshg112** [comment]
Sorry!
I found the solution to my problem and It's not related to jsdom.

1. I setted http as default adapter for axios.
![image](https://user-images.githubusercontent.com/15859884/43663273-81d342ea-972e-11e8-8028-1ede13009389.png)

2. If I have to send files, I use the xhr adapter.
![image](https://user-images.githubusercontent.com/15859884/43663320-b0e50b22-972e-11e8-9b29-2328065e42c8.png)

**Comment by thisgeek** [comment]
Readers who arrive at this thread may wish to refer to these sections of the current README:

- [Customizing jsdom](https://github.com/jsdom/jsdom#customizing-jsdom)
- Loading subresources: [basic options](https://github.com/jsdom/jsdom#basic-options)

Part of the first mentions that jsdom sets the url to `about:blank` by default. This in turn sets the value of `location.origin` to `null`, hence the error. Part of the second explicitly mentions that leaving it as such can prevent resources from loading, implying that it may help to change it to suit your needs. One alternative to @andreshg112's workaround is to configure jsdom with a url that is the same origin as the resources you are attempting to load. This fix has the benefit of having no particular connection to axios.

With mocha, for example, you can create a script that sets the url, then include its path the require list of your project's `.mocharc`. This example uses [rstacruz/jsdom-global](https://github.com/rstacruz/jsdom-global):

`./test/configure-jsdom.js`:
```javascript
require('jsdom-global')(undefined, {
  url: 'http://example.com'
})
```

`.mocharc.yaml`:
```yaml
require:
  - 'jsdom-global/register'
  - './test/configure-jsdom.js'
```
