### ISSUE TITLE
JSDOM tries to fetch external resources without resources: "usable" set when using document.implementation.createHTMLDocument

### ISSUE THREAD

**Issue by nrkn** [jsdom/jsdom#2374]
### Basic info:

- **Node.js version:** 10.11.0
- **jsdom version:** 12.1.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM('')
const { document } = dom.window
const doc = document.implementation.createHTMLDocument( '' )
const link = document.createElement( 'link' )

link.rel = 'stylesheet'
link.href = 'https://fonts.googleapis.com/css?family=Raleway:300,400,700,900|Work+Sans:300,400,700,900'

doc.head.appendChild( link )
```

```
TypeError: Cannot read property 'fetch' of null
    at PerDocumentResourceLoader.fetch (xxx\node_modules\jsdom\lib\jsdom\browser\resources\per-document-resource-loader.js:16:42)
    at fetchStylesheetInternal (xxx\node_modules\jsdom\lib\jsdom\living\helpers\stylesheets.js:77:18)
    at exports.fetchStylesheet (xxx\node_modules\jsdom\lib\jsdom\living\helpers\stylesheets.js:10:10)
    at obtainTheResource (xxx\node_modules\jsdom\lib\jsdom\living\nodes\HTMLLinkElement-impl.js:66:3)
    at HTMLLinkElementImpl._attach (xxx\node_modules\jsdom\lib\jsdom\living\nodes\HTMLLinkElement-impl.js:23:7)
    at HTMLHeadElementImpl.insertBefore (xxx\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:218:22)
    at HTMLHeadElementImpl.appendChild (xxx\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:316:17)
    at HTMLHeadElement.appendChild (xxx\node_modules\jsdom\lib\jsdom\living\generated\Node.js:276:47)
    at Object.<anonymous> (xxx\index.js:12:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

**Comment by domenic** [comment]
Nice find!

**Comment by jankapunkt** [comment]
Can confirm this and also got the same issue when including scripts with href to a cdn using similar code as the above.

**Comment by 7twin** [comment]
@retorquere until it gets reviewed by @domenic you can merge the fix in yourself locally: https://github.com/jsdom/jsdom/pull/2510

**Comment by AdriVanHoudt** [comment]
Is it possible this also needs a fix in `HTMLStyleElement-impl.js`?

Failing case:
```js
doc = new JSdom.JSDOM().window.document.implementation.createHTMLDocument();
htmlElement = doc.getElementsByTagName('html')[0];
htmlElement.innerHTML = `
    <style type="text/css">
        @import url('https://fonts.googleapis.com/css?family=Poppins:200,300,800');
    <style>
`;
```

**Comment by domenic** [comment]
Possible; please file a new issue with the full repro information (issue template).

**Comment by AdriVanHoudt** [comment]
Done, https://github.com/jsdom/jsdom/issues/2553.
Thanks for the super fast reply :O ✨
