### ISSUE TITLE
Tab characters in XHTML throws an exception when serialized

### ISSUE THREAD

**Issue by yvt** [jsdom/jsdom#2489]
### Basic info:

- **Node.js version:** `v10.11.0`
- **jsdom version:** `13.1.0`

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
    // Must be XHTML for this issue to occur
    contentType: 'application/xhtml+xml',
};
const dom = new JSDOM(`
<dummy />
`, options);

const e = dom.window.document.createElement('el');
e.appendChild(dom.window.document.createTextNode('\t'));
console.log(e.outerHTML);
```

Output:

```
/above/reproduction/code/node_modules/w3c-xmlserializer/lib/serialization.js:368
    throw new DOMException(
    ^
InvalidStateError: Failed to serialize XML: Node data is not well formed
    at module.exports.produceXMLSerialization (/above/reproduction/code/node_modules/w3c-xmlserializer/lib/serialization.js:368:11)
    at module.exports.fragmentSerialization (/above/reproduction/code/node_modules/jsdom/lib/jsdom/living/domparsing/serialization.js:33:19)
    at HTMLUnknownElementImpl.get outerHTML [as outerHTML] (/above/reproduction/code/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:149:12)
    at HTMLUnknownElement.get outerHTML [as outerHTML] (/above/reproduction/code/node_modules/jsdom/lib/jsdom/living/generated/Element.js:995:22)
    at Object.<anonymous> (/above/reproduction/code/reprod.js:12:15)
...
```

### How does similar code behave in browsers?

Outputs `"<el xmlns=\"http://www.w3.org/1999/xhtml\">\t</el>"`. See [this XHTML page](https://gist.github.com/yvt/604438ed9a30faab8c872a2cb7c2edbd).

**Comment by Zirro** [comment]
The solution to this should be to replace `\x20` with `\x09` on [line 9 in this file](https://github.com/jsdom/w3c-xmlserializer/blob/master/lib/serialization.js#L9), following https://www.w3.org/TR/xml/#char32. It'll also need a new test case.

@Sebmaster, in case you have time to look at this.
