### ISSUE TITLE
Calling input.blur() fails if input was focused

### ISSUE THREAD

**Issue by Rich-Harris** [jsdom/jsdom#2499]
### Basic info:

- **Node.js version:** 11.6.0
- **jsdom version:** 13.2.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const { window } = new JSDOM();
const { document } = window;

const input = document.createElement('input');
input.focus();
input.blur();
```

This results in a "Cannot read property '_defaultView' of undefined" error:

```
[project]/node_modules/jsdom/lib/jsdom/living/helpers/focusing.js:71
    view: target._ownerDocument._defaultView,
                                ^

TypeError: Cannot read property '_defaultView' of undefined
    at Object.exports.fireFocusEventWithTargetAdjustment ([project]/node_modules/jsdom/lib/jsdom/living/helpers/focusing.js:71:33)
    at HTMLInputElementImpl.blur ([project]/node_modules/jsdom/lib/jsdom/living/nodes/HTMLAndSVGElementShared-impl.js:52:14)
    at HTMLInputElement.blur ([project]/node_modules/jsdom/lib/jsdom/living/generated/HTMLElement.js:38:23)
    at Object.<anonymous> ([project]/index.js:8:7)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
```

**Comment by Rich-Harris** [comment]
(Should have added: this works in v12, just not in v13.)

**Comment by danielhusar** [comment]
+1 I see the same issue

**Comment by Zirro** [comment]
Thanks for the reports! This will be fixed by https://github.com/jsdom/jsdom/pull/2503.

**Comment by Rich-Harris** [comment]
Excellent, thank you

**Comment by asturur** [comment]
see the same issue.

**Comment by diegohaz** [comment]
Is it possible to release a patch on `v13` for this fix?

**Comment by domenic** [comment]
No, development has moved on to v14.

**Comment by asturur** [comment]
breaking changes for v14 are relatively small, update to 14 should be easy.

**Comment by diegohaz** [comment]
I'm using [jest-environment-jsdom-thirteen](https://github.com/theneva/jest-environment-jsdom-thirteen), which has dependency on `v13`.

I guess I'm just gonna drop it and add this to my package.json:
```json
"resolutions": {
  "jsdom": "14.0.0"
}
```

**Comment by asturur** [comment]
oh cool, what version of jest has jsdom 13?  i have jest 24 and it does not seems to use it, still at 11.

**Comment by diegohaz** [comment]
Jest didn't update jsdom. That's why I was using `jest-environment-jsdom-thirteen`.
