### ISSUE TITLE
JSDOM.fromURL Behaves differently on DigitalOcean (Ubuntu) than Mac

### ISSUE THREAD

**Issue by CunningDJ** [jsdom/jsdom#2507]
## Problem
When I run the following code (see Minimal Reproduction Case) on my **Macbook**, it grabs and parses the Google homepage with no problems.  When I run it on **DigitalOcean (Ubuntu)**, I get `undefined:1:532: malformed character entity.` error.  Why the difference?  Info for both machines below.

On Ubuntu, **not all URLs** give me this error, just some, like `https://google.com`, and this same address doesn't give me the error on Mac.

### Basic info:
**Ubuntu**
- **Node.js version:** 10.12.0
- `lsb-release`:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

**Macbook**
- **Node.js version:** 11.8.0

**Both**
- **jsdom version:** 13.2.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

// NO OPTIONS

JSDOM.fromURL('https://google.com')
  .then((dom) => { ... })
  .catch((err) => { console.error(err); })
```

**Comment by CunningDJ** [comment]
Full stack trace:
```
Error: undefined:1:532: malformed character entity.
    at SaxesParser.fail (/home/david/prod/sites/web-dossier/backend/node_modules/saxes/lib/saxes.js:487:18)
    at SaxesParser.parseEntity (/home/david/prod/sites/web-dossier/backend/node_modules/saxes/lib/saxes.js:1871:12)
    at SaxesParser.sEntityRest (/home/david/prod/sites/web-dossier/backend/node_modules/saxes/lib/saxes.js:1569:27)
    at SaxesParser.write (/home/david/prod/sites/web-dossier/backend/node_modules/saxes/lib/saxes.js:538:23)
    at HTMLToDOM._parseWithSaxes (/home/david/prod/sites/web-dossier/backend/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:171:12)
    at HTMLToDOM._doParse (/home/david/prod/sites/web-dossier/backend/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:48:75)
    at HTMLToDOM.appendToDocument (/home/david/prod/sites/web-dossier/backend/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:44:17)
    at new JSDOM (/home/david/prod/sites/web-dossier/backend/node_modules/jsdom/lib/api.js:45:29)
    at req.then.body (/home/david/prod/sites/web-dossier/backend/node_modules/jsdom/lib/api.js:146:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by CunningDJ** [comment]
Full stack trace:
```
Error: undefined:1:532: malformed character entity.
    at SaxesParser.fail ([...]/node_modules/saxes/lib/saxes.js:487:18)
    at SaxesParser.parseEntity ([...]/node_modules/saxes/lib/saxes.js:1871:12)
    at SaxesParser.sEntityRest ([...]/node_modules/saxes/lib/saxes.js:1569:27)
    at SaxesParser.write ([...]/node_modules/saxes/lib/saxes.js:538:23)
    at HTMLToDOM._parseWithSaxes ([...]/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:171:12)
    at HTMLToDOM._doParse ([...]/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:48:75)
    at HTMLToDOM.appendToDocument ([...]/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:44:17)
    at new JSDOM ([...]/node_modules/jsdom/lib/api.js:45:29)
    at req.then.body ([...]/node_modules/jsdom/lib/api.js:146:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by domenic** [comment]
It sounds likely that your server has some sort of proxy which is messing with the returned character data, thus making parsing impossible.

**Comment by CunningDJ** [comment]
@domenic the server is DigitalOcean.  I did not set up a proxy, and I don't believe they do either.  I ran it directly on the Node command line and had the same issue as with the Apache-forwarded Node service.

**Comment by jasmeeto** [comment]
I tested this on my Windows machine, and on a Ubuntu VM and was able to reproduce on both. Is there anything the library that is OS specific that would affect the encoding or character processing?

**Comment by rturnbull** [comment]
Did you resolve this? I have the same issue.
