### ISSUE TITLE
Resource Loader and disk files

### ISSUE THREAD

**Issue by asturur** [jsdom/jsdom#2525]
### Basic info:

- **Node.js version: 10.14** 
- **jsdom version:** 13.2

### Minimal reproduction case

```js
const jsdom = require('jsdom');
const jsdomWindow = new jsdom.JSDOM(
  decodeURIComponent('%3C!DOCTYPE%20html%3E%3Chtml%3E%3Chead%3E%3C%2Fhead%3E%3Cbody%3E%3C%2Fbody%3E%3C%2Fhtml%3E'),
  {
    features: {
      FetchExternalResources: ['img']
    },
    resources: 'usable'
  }).window;
const document = jsdomWindow.document;
const img = document.createElement('img');
img.onload = function() {
  console.log(img.src)
}
img.src = __dirname + './test/fixtures/test_image.gif';
```

this is the error i get

```
Error: Could not load img: "/Users/abogazzi/fabric/fabric.js./test/fixtures/test_image.gif"
    at onErrorWrapped (/Users/abogazzi/fabric/fabric.js/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:38:19)
    at Object.check (/Users/abogazzi/fabric/fabric.js/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:72:23)
    at request.then.catch.err (/Users/abogazzi/fabric/fabric.js/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:124:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3) Error: Tried to fetch invalid URL /Users/abogazzi/fabric/fabric.js./test/fixtures/test_image.gif
    at ResourceLoader.fetch (/Users/abogazzi/fabric/fabric.js/node_modules/jsdom/lib/jsdom/browser/resources/resource-loader.js:84:29)
    at PerDocumentResourceLoader.fetch (/Users/abogazzi/fabric/fabric.js/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:17:42)
    at HTMLImageElementImpl._attrModified (/Users/abogazzi/fabric/fabric.js/node_modules/jsdom/lib/jsdom/living/nodes/HTMLImageElement-impl.js:39:36)
    at Object.exports.appendAttribute (/Users/abogazzi/fabric/fabric.js/node_modules/jsdom/lib/jsdom/living/attributes.js:60:11)
    at HTMLImageElementImpl.setAttribute (/Users/abogazzi/fabric/fabric.js/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:243:18)
    at HTMLImageElementImpl.set src [as src] (/Users/abogazzi/fabric/fabric.js/node_modules/jsdom/lib/jsdom/living/nodes/HTMLImageElement-impl.js:61:10)
    at HTMLImageElement.set src [as src] (/Users/abogazzi/fabric/fabric.js/node_modules/jsdom/lib/jsdom/living/generated/HTMLImageElement.js:52:23)
    at Object.<anonymous> (/Users/abogazzi/fabric/fabric.js/test.js:15:9)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
```

Now i m just moving away from jsdom 9 and canvas 1.x where this was working flawlessly.
I understand this is related to the new resource loader and probably the need for a custom fetch method.

I would like to understand if loading files from disk with absolute path is still supported, or if it never was and before  as a side effect it was working correctly.

Any help to migrate my code is appreciated. Thanks.

**Comment by asturur** [comment]
Looks like that adding `file://` in front of the old pathnames is all i need.
Did not think of trying this soon enough.
