### ISSUE TITLE
jsdom throws `Cannot read property 'fetch' of null` when trying to fetch @import rules from a `createHTMLDocument` document

### ISSUE THREAD

**Issue by AdriVanHoudt** [jsdom/jsdom#2553]
### Basic info:

- **Node.js version:** 8.15.0
- **jsdom version:** 14

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

doc = new JSDOM().window.document.implementation.createHTMLDocument();
htmlElement = doc.getElementsByTagName('html')[0];
htmlElement.innerHTML = `
    <style type="text/css">
        @import url('https://fonts.googleapis.com/css?family=Poppins:200,300,800');
    <style>
`;
```

resulting stack trace
```js
.../node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:17
    const request = this._resourceLoader.fetch(url, {
                                         ^

TypeError: Cannot read property 'fetch' of null
    at PerDocumentResourceLoader.fetch (.../node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:17:42)
    at fetchStylesheetInternal (.../node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:77:18)
    at scanForImportRules (.../node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:109:9)
    at exports.createStylesheet (.../node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:43:3)
    at HTMLStyleElementImpl._updateAStyleBlock (.../node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:67:5)
    at HTMLStyleElementImpl._attach (.../node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:19:12)
    at HTMLHeadElementImpl._attach (.../node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:235:15)
    at HTMLHeadElementImpl._attach (.../node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:88:11)
    at HTMLHtmlElementImpl._insert (.../node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:701:14)
    at HTMLHtmlElementImpl._preInsert (.../node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:644:10)
```

What I think is happening is that `createHTMLDocument` does not give the resulting document a `_defaultView` which makes it so that the resource loader won't have a `_resourceLoader` (see https://github.com/jsdom/jsdom/blob/9a382982d8ab1f498b4e789fd16d494b1f37ebbb/lib/jsdom/browser/resources/per-document-resource-loader.js#L9) which then errors when it tries to fetch the import (https://github.com/jsdom/jsdom/blob/9a382982d8ab1f498b4e789fd16d494b1f37ebbb/lib/jsdom/browser/resources/per-document-resource-loader.js#L17)

This is related to https://github.com/jsdom/jsdom/issues/2374, where the issue was a link element resulting in the same error.

### How does similar code behave in browsers?

It doesn't throw (tested in Chrome 73 on macOS)

**Comment by AdriVanHoudt** [comment]
Thans for fixing this! 🎉
