### ISSUE TITLE
JSDOM does not typecheck attributes

### ISSUE THREAD

**Issue by tarjei** [jsdom/jsdom#2554]
### Basic info:

- **Node.js version:** 10.15
- **jsdom version:** 14.0.0

### Minimal reproduction case
```
const { JSDOM } = require('jsdom')

var jsdom = require('jsdom')

var jsdom = new jsdom.JSDOM(
  `<div>
      <progress
        class="StudyPlan-load-progress svelte-g1ijzk"
        value="0"
        max="100"
      />
    </div>`,
  {
    url: 'http://localhost',
    pretendToBeVisual: true,
  }
)
var window = jsdom.window

window.document.querySelector('.StudyPlan-load-progress').value = 0

console.log(window.document.body.innerHTML)
```

Output:

```
$ node /tmp/testcase.js
0
/tmp/node_modules/parse5/lib/serializer/index.js:168
    str = str.replace(AMP_REGEX, '&amp;').replace(NBSP_REGEX, '&nbsp;');
              ^

TypeError: str.replace is not a function
    at Function.Serializer.escapeString (/tmp/node_modules/parse5/lib/serializer/index.js:168:15)
    at Serializer._serializeAttributes (/tmp/node_modules/parse5/lib/serializer/index.js:103:38)
    at Serializer._serializeElement (/tmp/node_modules/parse5/lib/serializer/index.js:67:14)
    at Serializer._serializeChildNodes (/tmp/node_modules/parse5/lib/serializer/index.js:50:26)
    at Serializer._serializeElement (/tmp/node_modules/parse5/lib/serializer/index.js:93:18)
    at Serializer._serializeChildNodes (/tmp/node_modules/parse5/lib/serializer/index.js:50:26)
    at Serializer.serialize (/tmp/node_modules/parse5/lib/serializer/index.js:36:14)
    at Object.exports.serialize (/tmp/node_modules/parse5/lib/index.js:28:23)
    at htmlSerialization (/tmp/node_modules/jsdom/lib/jsdom/living/domparsing/serialization.js:20:17)
    at module.exports.fragmentSerialization (/tmp/node_modules/jsdom/lib/jsdom/living/domparsing/serialization.js:27:12)

```

### How does similar code behave in browsers?

The browser will return different types based how you call it: 

![Selection_005](https://user-images.githubusercontent.com/211263/56150755-dccf4f00-5faf-11e9-847e-e86a9dbf3977.png)

Is parse5 using the wrong api when accessing the value?

**Comment by domenic** [comment]
The problem appears to be our implementation of HTMLProgressElement calls `this.setAttribute("value", value)` without first converting `value` to a string. This seems to be a widespread problem whereever we manually re-implement attribute reflection. (E.g., same problem with HTMLProgressElement's `max`.)

I think the solution will be to force string conversion, even on the internal calls, because of how much we use them this way. I'll be curious on other collaborators thoughts. I'll post a patch once #2547 lands (since it touches similar code).
