### ISSUE TITLE
Jsdom failed to parse http://instagram.com photo

### ISSUE THREAD

**Issue by beshoo** [jsdom/jsdom#2578]
I am trying to scrap my personal photos but when I call Instagram photo I have this javascript errors, while there is no error in chrome console!

### Basic info:
- **Node.js version:** 10.15.3
- **jsdom version:** 15
### Minimal reproduction case
```
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const resourceLoader = new jsdom.ResourceLoader({
  strictSSL: false,
  userAgent: "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36",
});
         
const options = {
  resources: resourceLoader,
  runScripts: 'dangerously',
  pretendToBeVisual: true,
  //virtualConsole: new jsdom.VirtualConsole(),
  cookieJar: new jsdom.CookieJar(),
  beforeParse(window) {
    //console.log(window);
  }
}

const { window } = JSDOM.fromURL("https://www.instagram.com/p/Bv2SJ0FFMiK/",  options ).then(dom => {
	console.log(dom.serialize());
}).catch((err) => { console.error(err); });
```

**Error To the Console:**
```
TypeError: i(...) is not a constructor
    at a.useState (https://www.instagram.com/static/bundles/es6/Consumer.js/175fefa0cc6c.js:238:660)
    at Object.useState (https://www.instagram.com/static/bundles/es6/Vendor.js/1254883211b5.js:11:98833)
    at Object.useState (https://www.instagram.com/static/bundles/es6/Vendor.js/1254883211b5.js:8:5598)
    at e.default (https://www.instagram.com/static/bundles/es6/Consumer.js/175fefa0cc6c.js:238:647)
    at o (https://www.instagram.com/static/bundles/es6/Consumer.js/175fefa0cc6c.js:224:582)
    at e.ViewpointClipRegion.t (https://www.instagram.com/static/bundles/es6/Consumer.js/175fefa0cc6c.js:224:1260)
    at dn (https://www.instagram.com/static/bundles/es6/Vendor.js/1254883211b5.js:11:35682)
    at Vn (https://www.instagram.com/static/bundles/es6/Vendor.js/1254883211b5.js:11:46128)
    at _r (https://www.instagram.com/static/bundles/es6/Vendor.js/1254883211b5.js:11:66990)
    at Sr (https://www.instagram.com/static/bundles/es6/Vendor.js/1254883211b5.js:11:67375)
(node:616) UnhandledPromiseRejectionWarning: TypeError: i(...) is not a constructor
(node:616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Please, Advice how can I imitate chrome behaviors!

**Comment by pmdartus** [comment]
After some investigation, there is a bug in instagram `DOMRect` polyfill. You can reproduce the same error in any browser by deleting the `DOMRect` constructor before any javascript gets executed.

I have created a specific issue to track the implementation of the Geometry Interfaces spec (https://github.com/jsdom/jsdom/issues/2716), which defines the `DOMRect` interface.
