### ISSUE TITLE
Error requiring jsdom with node --external-modules flag

### ISSUE THREAD

**Issue by fasttime** [jsdom/jsdom#2579]
### Basic info:

- **Node.js version:** 12.2.0
- **jsdom version:** latest

### Minimal reproduction case

```js
#!/usr/bin/env node --experimental-modules
require("jsdom");
```
---

I can't seem to find a suitable duplicate, so I'm posting this as a new issue.

When node is launched with the `--experimental-modules` option, any `require`/`import` statements referencing jsdom result in an error:

```
TypeError: Cannot read property 'onReady' of undefined
    at Module.load (internal/modules/cjs/loader.js:638:22)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (${PWD}/node_modules/psl/index.js:14:19)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
```

I was able to fix the error by patching a file, but this won't work for the general case.

```diff
--- a/lib/jsdom/browser/resources/resource-loader.js
+++ b/lib/jsdom/browser/resources/resource-loader.js
@@ -5 +5 @@ const dataURLFromRecord = require("data-urls").fromURLRecord;
-const request = require("request-promise-native");
+const request = require("request");
```

**Comment by fasttime** [comment]
This seems to be fixed now: nodejs/node/pull/25491
