### ISSUE TITLE
'Error: undefined:1:535: malformed character entity' when trying to navigate to google

### ISSUE THREAD

**Issue by miggs125** [jsdom/jsdom#2606]
### Basic info:

- **Node.js version:** 10.15.3
- **jsdom version:** 13.2.0
### Minimal reproduction case

```js
async function goToGoogle() {
  const myResourceLoader = new ResourceLoader({
    strictSSL: true
  });
  try {
    let dom = await JSDOM.fromURL('https://www.google.com', {
      resources: myResourceLoader,
    });
  }catch(err) {
    console.log(err);
  }
}


goToGoogle();
```

Error produced: 

Error: undefined:1:535: malformed character entity.
    at SaxesParser.fail (/home/.../node_modules/saxes/lib/saxes.js:487:18)
    at SaxesParser.parseEntity (/home/.../node_modules/saxes/lib/saxes.js:1871:12)
    at SaxesParser.sEntityRest (/home/.../node_modules/saxes/lib/saxes.js:1569:27)
    at SaxesParser.write (/home/.../node_modules/saxes/lib/saxes.js:538:23)
    at HTMLToDOM._parseWithSaxes (/home/.../node_modules/jsdom/lib/jsdom/browser/htmltodom.js:171:12)
    at HTMLToDOM._doParse (/home/.../node_modules/jsdom/lib/jsdom/browser/htmltodom.js:48:75)
    at HTMLToDOM.appendToDocument (/home/.../node_modules/jsdom/lib/jsdom/browser/htmltodom.js:44:17)
    at new JSDOM (/home/.../node_modules/jsdom/lib/api.js:45:29)
    at req.then.body (/home/.../node_modules/jsdom/lib/api.js:146:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)

### How does similar code behave in browsers?
browsers navigate without any issue to google.com

**Comment by lddubeau** [comment]
Thanks for the report.

I'm the author of saxes. Are you still able to reproduce that issue. I cannot reproduce it here. If you can reproduce it please include the URL to a complete GitHub repository that reproduces the problem. Chances are that I fixed it while I was fixing something else.
