### ISSUE TITLE
Help me understand the new JSdom API

### ISSUE THREAD

**Issue by termitek12** [jsdom/jsdom#2624]
### Basic info:

node v8.10.0

### Minimal reproduction case

Why does new API throw errors?

"Error: Not implemented: window.scrollTo"
"Error: Uncaught [TypeError: Cannot read property 'origin' of undefined]"
"Error: Uncaught [TypeError: Cannot read property 'removeAttribute' of null]"
etc.

OLD API (works fine); [jsdom v11.3.0]

```
var jsdom = require("jsdom/lib/old-api.js");
var url = 'https://www.wp.pl';

var requestData = request(url, function(err, resp, HTMLdata) {
	if (!err && resp.statusCode === 200) {
		console.log('Request success - we render jsdom page \n');
		jsdom.env({
			html: HTMLdata,
			features: {
				FetchExternalResources : ['script'],
				ProcessExternalResources : ['script'],
				SkipExternalResources: false
			},
			done: function (err, window) {
				if (err) {console.log('ERR: ' + err);}
				var document = window.document;
				window.close();
			}
		});
	}
});
```

NEW API: [jsdom v15.1.1]

```
const jsdom = require('jsdom');
const {JSDOM} = jsdom;

var url = 'https://www.wp.pl';
var requestData = request(url, function(err, resp, HTMLdata)
{
	if (!err && resp.statusCode === 200){
		console.log('Request success - we render jsdom page \n');

		var JSdom1 = new JSDOM(HTMLdata,
		{
			url : url,
			referrer : url,
			runScripts : 'dangerously',
			resources : 'usable'
		});
		if (JSdom1.onload){}
	}
});
```

for example because of new API:

"%cWarning! background:red;color:white;font-weight:bold; WPJSlib is embedded incorrectly, probably 'src' is incorrectly extended. Contact ATFD for further information."

What I'm doing wrong? Any idea how to fix that?

**Comment by yuki-93** [comment]
I Have the same issue. I use jsdom with karma-runner and the karma-jsdom-launcher. With version 8.0 of the karma launcher, this error starts to be thrown in output. I also updated jsdom directly, but this error seems to stay.
If this issue is not related to jsdom itself, just leave me a comment, then i'll open an issue at karma.

Versions:
jsdom@15.1.1
karma-jsdom-launcher@8.0.0
karam@4.3.0

Here is my output:
```
.04 10 2019 12:32:50.700:INFO [launcher]: Starting browser jsdom
.Error: Uncaught [TypeError: Cannot read property 'origin' of undefined]
    at reportException (/var/www/project/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
    at innerInvokeEventListeners (/var/www/project/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:332:9)
    at invokeEventListeners (/var/www/project/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
    at EventTargetImpl._dispatch (/var/www/project/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
    at fireAnEvent (/var/www/coredata/node_modules/jsdom/lib/jsdom/living/helpers/events.js:17:36)
    at Timeout.setTimeout [as _onTimeout] (/var/www/project/node_modules/jsdom/lib/jsdom/living/post-message.js:30:5)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) TypeError: Cannot read property 'origin' of undefined
    at handleMessage (http://localhost:9876/karma.js:45:52)
    at innerInvokeEventListeners (/var/www/project/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:316:27)
    at invokeEventListeners (/var/www/project/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
    at EventTargetImpl._dispatch (/var/www/project/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
    at fireAnEvent (/var/www/coredata/node_modules/jsdom/lib/jsdom/living/helpers/events.js:17:36)
    at Timeout.setTimeout [as _onTimeout] (/var/www/project/node_modules/jsdom/lib/jsdom/living/post-message.js:30:5)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

```

**Comment by yuki-93** [comment]
I looked into the source of karma, the issue results from the /var/www/project/node_modules/karma/static/karma.js file (lines 39 and following) in the following listing. I think the issue is from jsdom, the there is no evt-Object for the message-Event. With other browsers, like chromium and firefox, karam doesn't throw in issue here.

```
// Set up postMessage bindings for current window
  // DEV: These are to allow windows in separate processes execute local tasks
  //   Electron is one of these environments
  if (window.addEventListener) {
    window.addEventListener('message', function handleMessage (evt) {
      // Resolve the origin of our message
      var origin = evt.origin || evt.originalEvent.origin

      // If the message isn't from our host, then reject it
      if (origin !== window.location.origin) {
        return
      }

      // Take action based on the message type
      var method = evt.data.__karmaMethod
      if (method) {
        if (!self[method]) {
          self.error('Received `postMessage` for "' + method + '" but the method doesn\'t exist')
          return
        }
        self[method].apply(self, evt.data.__karmaArguments)
      }
    }, false)
  }
```
