### ISSUE TITLE
TypeError: Cannot read property '_ownerDocument' of undefined

### ISSUE THREAD

**Issue by level09** [jsdom/jsdom#266]
/usr/local/lib/node/.npm/jsdom/0.2.1/package/lib/jsdom/level1/core.js:458
    if (!newChild._ownerDocument) newChild._ownerDocument = this._ownerDocumen
                 ^
TypeError: Cannot read property '_ownerDocument' of undefined
    at Object.<anonymous> (/usr/local/lib/node/.npm/jsdom/0.2.1/package/lib/jsdom/level1/core.js:458:18)
    at Object.insertBefore (/usr/local/lib/node/.npm/jsdom/0.2.1/package/lib/jsdom/level2/events.js:325:20)
    at Object.appendChild (/usr/local/lib/node/.npm/jsdom/0.2.1/package/lib/jsdom/level1/core.js:574:17)
    at setChild (/usr/local/lib/node/.npm/jsdom/0.2.1/package/lib/jsdom/browser/htmltodom.js:167:17)
    at setChild (/usr/local/lib/node/.npm/jsdom/0.2.1/package/lib/jsdom/browser/htmltodom.js:163:7)
    at setChild (/usr/local/lib/node/.npm/jsdom/0.2.1/package/lib/jsdom/browser/htmltodom.js:163:7)
    at setChild (/usr/local/lib/node/.npm/jsdom/0.2.1/package/lib/jsdom/browser/htmltodom.js:163:7)
    at setChild (/usr/local/lib/node/.npm/jsdom/0.2.1/package/lib/jsdom/browser/htmltodom.js:163:7)
    at setChild (/usr/local/lib/node/.npm/jsdom/0.2.1/package/lib/jsdom/browser/htmltodom.js:163:7)
    at setChild (/usr/local/lib/node/.npm/jsdom/0.2.1/package/lib/jsdom/browser/htmltodom.js:163:7)

**Comment by GianlucaGuarini** [comment]
I still have this issue by using a custom html tag:
```javascript
jsdom.env('<!doctype html><html><head></head><body><' + myComponent +'/></body></html>', function (errors, window) {
  global.document = window.document
  console.log(document.body.innerHTML) // <my-component></my-component>
})
```

**Comment by domenic** [comment]
@GianlucaGuarini please open a new bug instead of commenting on an old bug; include the full error thrown with the stack trace, and make sure you are using the latest version of jsdom, 4.0.1 on io.js.
