### ISSUE TITLE
Repeated selectors error

### ISSUE THREAD

**Issue by dy** [jsdom/jsdom#2680]
Querying repeated selectors like `.a, .a, .b` gives error:
```js
C:\projects\spect\node_modules\nwsapi\src\nwsapi.js:1522
        list = r && h[i] ? h[i]() : compat[n[i][0]](context, n[i].slice(1))();
                                               ^
TypeError: Cannot read property '0' of undefined
    at results_from (C:\projects\spect\node_modules\?[4mnwsapi?[24m\src\nwsapi.js:1522:48)
    at Object._querySelectorAll [as select] (C:\projects\spect\node_modules\?[4mnwsapi?[24m\src\
nwsapi.js:1499:15)
    at HTMLDivElementImpl.querySelectorAll (C:\projects\spect\node_modules\?[4mjsdom?[24m\lib\js
dom\living\nodes\ParentNode-impl.js:72:26)
    at HTMLDivElement.querySelectorAll (C:\projects\spect\node_modules\?[4mjsdom?[24m\lib\jsdom\
living\generated\Element.js:835:47)
    at Object.<anonymous> (C:\projects\spect\jsdom.js:5:42)
```

### Basic info:

- **Node.js version:** 12.5.0
- **jsdom version:** 15.1.1

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom")
const dom = new JSDOM(``, {});
dom.window.document.createElement('div').querySelectorAll('.foo, .foo, .bar')
```

### How does similar code behave in browsers?

Just open console and see the result:

<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>
```js
document.createElement('div').querySelectorAll('.foo, .foo, .bar')
```

**Comment by pmdartus** [comment]
Thanks for reporting this issue. I am not able to reproduce the issue on either `15.1.1` or `15.2.1` (latest version of jsdom). The query selector library used in jsdom has been updated with in the latest release. 

@dy Could you verify if you can still reproduce the same issue on the latest version of jsdom?

**Comment by dy** [comment]
It works ok now,

**Comment by dy** [comment]
It is broken again. To reproduce the error:
```js
const { JSDOM } = require("jsdom")
const dom = new JSDOM(``, {});
let el = document.createElement('div')
el.querySelectorAll('.foo, .foo, .bar') // this is fine
el.querySelectorAll('.foo, .foo, .bar') // this throws error!
```
@pmdartus

**Comment by pmdartus** [comment]
Jsdom uses nwsapi as CSS selector engine. I was able to reproduce the bug independently of jsdom ([issue](https://github.com/dperini/nwsapi/issues/32)). Let's keep the issue open until we bump this issue is fixed and we update nwsapi version in jsdom.
