### ISSUE TITLE
TypeError: client.abort is not a function

### ISSUE THREAD

**Issue by kaiyoma** [jsdom/jsdom#2685]
- **Node.js version:** 10.16.0
- **jsdom version:** 15.1.1

I've started running into this error lately while running the unit tests for my project:

```
● Test suite failed to run

  TypeError: client.abort is not a function

    at XMLHttpRequest.abort (node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:379:16)
    at JSDOMEnvironmentGlobal.teardown (node_modules/jest-environment-jsdom-global/environment.js:13:18)
```

Before I try to come up with a minimal repro, I wanted to post just this first. Is this a known issue? Seems to happen quite regularly on Windows 10, but not on macOS/Linux.

**Comment by domenic** [comment]
Not enough information to reproduce.
