### ISSUE TITLE
getComputedStyle() does not return default values, e.g svg.fill is "" instead of "rgb(0, 0, 0)"

### ISSUE THREAD

**Issue by sermunar** [jsdom/jsdom#2688]
### Basic info:

I try to get the "refreshed" cssStyleDeclaration values of a new created SVGNode after appendig it to document.body.

- **Node.js version:** v8.16.0
- **jsdom version:** 9.4.0 and 15.2.0

- **A. Behaviour in node with jsdom^9.4.0**: 
CSSStyleDeclaration returned by getComputedStyle() is not getting refreshed after appendig it to document.body. e.g. fill = "" //<- should be rgb(0, 0, 0)

gist: https://gist.github.com/sermunar/2625a4557796e50c2d1e121341610dc7#file-js-esnext-for-jsdom-9-4-0-js

- **B.1. Behaviour in node with jsdom@latest (15.2.0)**: 
getComputedStyle() crashes and throws an error: 

gist: https://gist.github.com/sermunar/2625a4557796e50c2d1e121341610dc7#file-ts-3-6-4-for-jsdom-15-2-0-ts

```
C:\test\node_modules\jsdom\lib\jsdom\browser\Window.js:520
    forEach.call(style, property => {
            ^

TypeError: Array.prototype.forEach called on null or undefined
    at forEach (<anonymous>)
    at Window.getComputedStyle (C:\test\node_modules\jsdom\lib\jsdom\browser\Window.js:520:13)
    at Object.<anonymous> (C:\test\dist\index.js:14:33)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
```
- **B.2. workaround for issue in B.1. for jsdom@latest (15.2.0)**: getComputedStyle() does not crash but still returns unexpected values e.g. fill = "" //<- should be rgb(0, 0, 0)

After few debugging I realized DOMParsers behaves different between **9.4.0** and **15.2.0**.
In latest version **15.2.0** its necessary to call
```js
const node = new win.DOMParser().parseFromString('<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"><g></g></svg>','image/svg+xml');
```
instead of 
```js
const node = new win.DOMParser().parseFromString('<svg><g></g></svg>','image/svg+xml');
```
to get a valid SVGElement like in **9.4.0** and beeing able to call window.getComputedStyle(), but still it does not return the refreshed values like above **A**. e.g. fill = "" //<- should be rgb(0, 0, 0)

- **C. Behaviour in browser**: 
After appending the SVGNode, getComputedStyle() returns expected default style values. e.g. fill = "rgb(0, 0, 0)"
See fill definition https://www.w3.org/TR/SVG11/painting.html#FillProperty

### Minimal reproduction case

See https://gist.github.com/sermunar/2625a4557796e50c2d1e121341610dc7#file-js-esnext-for-jsdom-9-4-0-js
```js
"use strict";
//"jsdom": "^9.4.0"
const jsdom = require('jsdom');
const dom = jsdom.jsdom('<html><body></body></html>');

const win = dom.defaultView;
const doc = win.document;

const node = new win.DOMParser().parseFromString('<svg><g></g></svg>', 'image/svg+xml');
const svgNode = node.childNodes[0];

doc.body.appendChild(svgNode);

const cssStyleDeclaration = win.getComputedStyle(svgNode);
//cssStyleDeclaration.fill = ""
console.log(`fill: ${cssStyleDeclaration.fill}`); //"fill: " instead of "fill: rgb(0, 0, 0)"
```

### How does similar code behave in browsers?

getComputedStyle(svgNode) returns expected (refreshed) values.
e.g. fill is rgb(0, 0, 0) 
See fill definition https://www.w3.org/TR/SVG11/painting.html#FillProperty

jsbin: https://jsbin.com/qalamok/edit?html,js,console,output

**Comment by EmilePerron** [comment]
Has there been any updates or news regarding this issue? 
I'm facing a similar project and would like to know if a fix or a recommended workaround exists.

**Comment by domenic** [comment]
https://twitter.com/slicknet/status/782274190451671040

**Comment by EmilePerron** [comment]
Fair enough.

I'm looking into possible fixes... would adding the default styles for each tag in [`lib/jsdom/browser/default-stylesheet.js`](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/browser/default-stylesheet.js) be an accepted solution? Or would this  make maintenance of this file too difficult in the future? 

I guess we could also create a different stylesheet for the defaults, as I expect it will be quite a long and verbose file...

Does that make sense to you?
If so, I'll get to work on a PR.

**Comment by domenic** [comment]
Generally what's needed is to follow the specs. The default stylesheet for HTML is in various subsections of https://html.spec.whatwg.org/multipage/rendering.html#rendering , and for SVG it's https://svgwg.org/svg2-draft/styling.html#UAStyleSheet . To the extent `default-stylesheet.js` fails to match that, we'd be happy to accept updates.

Otherwise, if it's not derived from that, then likely the issue is our implementation of cascading, inheritance, and the CSS object model. That's spread out in various places, e.g. https://github.com/jsdom/cssstyle/ , and `Window.js` where `getComputedStyle()` is implemented. It might be the case that https://github.com/jsdom/jsdom/pull/2690 helps with that; unfortunately that PR got stuck mid-way through review, but it might be worth applying it locally and seeing if it fixes your problem, and if so, trying to revive it.

**Comment by EmilePerron** [comment]
Thanks for the detailed response!

I applied #2690 locally, but it didn't seem to fix this particular issue.
I'll dive into the specs you mentioned and report back as soon as I can 👍
