### ISSUE TITLE
Errors in onload event on iframe are not handled properly

### ISSUE THREAD

**Issue by pingwing** [jsdom/jsdom#2718]
I wasn't been able to create a reproduction for this, but maybe someone else will face the same issue.

Steps to reproduce:
1. Render an iframe in JSDOM
2. The onload handler for the frame threw an error
3. JSDOM threw this error:

```
./node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:327
      } else if (wrapper._ownerDocument) {
                         ^

TypeError: Cannot read property '_ownerDocument' of undefined
    at innerInvokeEventListeners (./node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:327:26)
    at invokeEventListeners (./node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
    at EventTargetImpl._dispatch (./node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
    at fireAnEvent (./node_modules/jsdom/lib/jsdom/living/helpers/events.js:17:36)
    at Window.process.nextTick (./node_modules/jsdom/lib/jsdom/browser/Window.js:608:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Looking at the code it looks like there is a missing null check on line 327 of EventTarget-impl.js. Even with the null check the underlying error would not be reported.

**Comment by domenic** [comment]
Can you please edit this post to fill out the issue template, including a minimal reproduction we can use? Then comment and we can reopen this.
