### ISSUE TITLE
Implement `SVGGElement`

### ISSUE THREAD

**Issue by khalyomede** [jsdom/jsdom#2734]
I guess SVGGElement ([MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/SVGGElement)) is not supported in jsdom ?

### Basic info:

- **Node.js version:** 10.150.
- **jsdom version:** 11.5.1

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
  ... your options here ...
};
const dom = new JSDOM(`
  <svg>
    <g id="g"> 
  </svg>
`, options);

const g = dom.window.document.querySelector("#g");

if (g instanceof SVGGElement) { // throws "SVGGElement is not defined"
  console.log("ok");
}
```

### How does similar code behave in browsers?

[https://jsfiddle.net/p3ag4v85/](https://jsfiddle.net/p3ag4v85/)

(check in the console and look for `ok`)

### Notes

I have to say that I noticed the bug when I tested my code using Jest, that is using jsdom internally. Here is the error I got:

```javascript
● should throw an Error if g element is not found

    expect(received).toThrowError(expected)

    Expected message: "group element not found"
    Received message: "SVGGElement is not defined"

          46 |         if (!(svgElement instanceof SVGSVGElement))
          47 |             throw new Error("svg element not found");
        > 48 |         if (!(groupElement instanceof SVGGElement))
             |                                       ^
          49 |             throw new Error("g element not found");
          50 |         this.groupElement = groupElement;
          51 |         this.groupBBoxWidth = 0;

          at new Lib (lib/js/index.js:48:39)
          at test/MyLib/constructor.test.js:86:15
          at Object.<anonymous> (node_modules/expect/build/toThrowMatchers.js:81:11)
          at Object.toThrowError (node_modules/expect/build/index.js:342:33)
          at Object.<anonymous> (test/MyLib/constructor.test.js:87:7)

      85 |     expect(
      86 |         () => new Lib({ svgIdentifier: "svg", groupIdentifier: "g" })
    > 87 |     ).toThrowError(new TypeError("group element not found"));
         |       ^
      88 | });
      89 | 

      at Object.<anonymous> (test/MyLib/constructor.test.js:87:7)
```

**Comment by domenic** [comment]
`SVGElement` is supported. However your code is looking up `SVGElement` in the Node.js global. You need to use `dom.window.SVGElement`.

**Comment by aminnairi** [comment]
Yep. This is indeed a bug. The specification does not seem to be correctly implemented for SVG groups.

```html
<!DOCTYPE html>
<html>
    <body>
        <svg id="svg">
            <g id="group"></g>
        </svg>
        <script>
            "use strict";

            window.addEventListener("load", function() {
                const svg = document.getElementById("svg");
                const group = document.getElementById("group");
                
                console.dir(svg.constructor);   // ƒ SVGSVGElement()
                console.dir(group.constructor); // ƒ SVGGElement()
            });
        </script>
    </body>
</html>
```

```javascript
"use strict";

const { JSDOM } = require("jsdom");

const dom = new JSDOM(`
    <svg id="svg">
        <g id="group"></g>
    </svg>
`);

const svg = dom.window.document.getElementById("svg");
const group = dom.window.document.getElementById("group");

console.log(svg.constructor);   // [Function: SVGSVGElement]
console.log(group.constructor); // [Function: SVGElement]
```

[GitHub reproduction repository](https://github.com/aminnairi/jsdom-svg-issue-demo).

**Comment by TimothyGu** [comment]
Indeed, looks like this is just because we don't support the SVG `g` element. Our SVG support isn't too great at the moment.

**Comment by BenHenning** [comment]
Out of curiosity, should `SVGElement` now be exported as part of globals with jsdom-global? We found recently after upgrading to jsdom 26.1.0 that, while `SVGElement` is indeed part of `window` it isn't available in the global namespace (and thus still leads to undefined type errors in production code that reference `SVGElement`). Looking at jsdom-global 3.0.2 `SVGElement` is not part of the generated `keys.js` file.

Happy to file a separate issue and/or send a PR if that's preferred to track this.

**Comment by domenic** [comment]
We don't provide support for third-party packages like `jsdom-global`. Especially since that package explicitly goes against our recommendations. https://github.com/jsdom/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global

**Comment by BenHenning** [comment]
Ah, it wasn't clear to me if `jsdom-global` was part of this project despite some digging, so the explicit mention is actually very helpful--thanks!

Apologies if this is the wrong place to discuss this, but out of curiosity for this best practice: I completely understand the argument for not polluting the global namespace in Node.js (though admittedly the risk of polluting it for tests that are run in isolated Node.js processes seems very low to me, but perhaps I'm missing something). That being said, this best practice does introduce an opposite problem: all production code that runs in browsers and references DOM classes/things now needs to start prefixing things with `window` or similar top-level DOM containers in order to access them correctly. That introduces an inconsistency with the rest of the web ecosystem (and likely compatibility issues with third-party libraries that do not or will not change to that pattern). That does have the effect of `jsdom` being less useful in those situations.

While I see there being potential issues with polluting the global namespace, the alternative seems potentially very difficult to manage so it makes complete sense to me why something like `jsdom-global` arose. Is the primary recommendation of this project to always wrap production code with `window` and other top-level container references despite these limitations? Or, is there another pattern possible here that avoids requiring production code to conform to a test environment restriction (though I know this is only semi-test environment as the real restriction has to do with Node.js not necessarily `jsdom`)?
