### ISSUE TITLE
Broken baseURI on attribute node

### ISSUE THREAD

**Issue by nin-jin** [jsdom/jsdom#2819]
### Basic info:

- **Node.js version:** 11.13.0
- **jsdom version:** 16.1.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const win = new JSDOM( '' , { url : 'https://localhost/' } ).window

const div = win.document.createElement( 'div' )
win.document.documentElement.appendChild( div )
div.setAttribute( 'dir' , 'rtl' )

const attr = div.getAttributeNode( 'dir' )
attr.baseURI // fails
```

```
Thrown:
TypeError: Cannot read property 'querySelector' of undefined
    at Object.exports.documentBaseURL.document [as documentBaseURL] (...\node_modules\jsdom\lib\jsdom\living\helpers\document-base-url.js:7:30)
    at exports.documentBaseURLSerialized.document (...\node_modules\jsdom\lib\jsdom\living\helpers\document-base-url.js:18:41)
    at AttrImpl.get baseURI [as baseURI] (...\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:365:12)
    at Attr.get baseURI [as baseURI] (...\node_modules\jsdom\lib\jsdom\living\generated\Node.js:432:24)
```

### How does similar code behave in browsers?

No error

**Comment by nin-jin** [comment]
I think broblem is there: https://github.com/jsdom/jsdom/commit/b8c7bb554daedcef5dc95c40451fe59f8bb71560
