### ISSUE TITLE
Set timeout to JSDOM.fromURL

### ISSUE THREAD

**Issue by Sarseth** [jsdom/jsdom#2824]
### Basic info:

- **Node.js version: 12.14.1** 
- **jsdom version: 16.1.0** 

### Minimal reproduction case

```js
thousandsOfLinksToOneServerThatHasSomeLimitations.forEach(link => {
    allDownloadTasks.push(
        try {
             let dom = await JSDOM.fromURL(url);
             //anything there
         } catch (error) {
             console.error(error); // <--- here I get error
         }
    ).;
});

```

### Stacktrace

```
RequestError: Error: connect ETIMEDOUT <SOMEIP>:443
    at new RequestError (D:\Workspace\backend\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\Workspace\backend\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\Workspace\backend\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\Workspace\backend\node_modules\request\request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.onRequestError (D:\Workspace\backend\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:223:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8) {
  name: 'RequestError',
  message: 'Error: connect ETIMEDOUT <SOMEIP>:443',
  cause: Error: connect ETIMEDOUT <SOMEIP>:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '<SOMEIP>',
    port: 443
  },
  error: Error: connect ETIMEDOUT <SOMEIP>:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '<SOMEIP>',
    port: 443
  },
  options: {
    encoding: null,
    gzip: true,
    jar: RequestJar { _jar: [CookieJar] },
    strictSSL: true,
    forever: true,
    headers: {
      'User-Agent': 'Mozilla/5.0 (win32) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/16.1.0',
      'Accept-Language': 'en',
      Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
    },
    uri: 'https://<desiredUrl>',
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}

```

### Description

After like hitting server with more than 400 requests it starts to answer me very slowly.
One thing is that I have to limit my requests per second, but above that I would like to setup timeout for JSDOM. And I think I found solution here: https://github.com/jsdom/jsdom/pull/2488
but question is, when it will be merged? :)

**Comment by M4shy** [comment]
knock knock, 2022 here :)

**Comment by M4shy** [comment]
Since my research, I've hit this topic many times... I was looking for alternative in case of setting up a timeout value during JSDOM invocations such as 'fromFile()' or 'fromURL()'. But I didn't figured out how to properly using them till I found a workaround. The 'Promise.race()' invocation might do the trick as it returns the first rejected/resolved 'Promise' from iterables (array).

const timer = new Promise((resolve, reject) => {
  setTimeout(() => reject("timeout !"), 200);
});
Promise yourPromise = YourProcessThatReturnsAPromise();

Promise.race([yourPromise, timer])
      .then((response) => {
            console.log(response);
       })
      .catch((err) => {
            console.log(err);
      });

//It should displays 'timeout !' if 'YourProcessThatReturnsAPromise()' doesn't respond before 200ms
