### ISSUE TITLE
Error about `cloneNode` of Attribute node

### ISSUE THREAD

**Issue by lovetingyuan** [jsdom/jsdom#2832]
### Basic info:

- **Node.js version:** 12.8.1
- **jsdom version:** 16.1.0
### Minimal reproduction case
> Changed Attr to extend Node, to align with specifications. (ExE-Boss)
```js
const { JSDOM } = require('jsdom')

new JSDOM(`
<!DOCTYPE html>
<html lang="en">
<body>
<p id="foo" data-a-b=""></p>
<script>
document.getElementById('foo').getAttributeNode('data-a-b').cloneNode(true)
</script>
</body>
</html>

`, {
  runScripts: 'dangerously'
})

```

error output
```bash
Error: Uncaught [TypeError: Cannot read property '_createAttribute' of undefined]
    at reportException (example-app\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:62:24)
    at processJavaScript (example-app\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:243:7)
    at HTMLScriptElementImpl._innerEval (example-app\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:168:5)
    at example-app\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:107:12
    at ResourceQueue.push (example-app\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:53:16)
    at HTMLScriptElementImpl._fetchInternalScript (example-app\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:106:21)
    at HTMLScriptElementImpl._eval (example-app\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:162:12)
    at HTMLScriptElementImpl._poppedOffStackOfOpenElements (example-app\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:125:10)
    at OpenElementStack.JSDOMParse5Adapter.OpenElementStack.pop (example-app\node_modules\jsdom\lib\jsdom\browser\parser\html.js:46:16)
    at Object.endTagInText [as END_TAG_TOKEN] (example-app\node_modules\parse5\lib\parser\index.js:2153:20) TypeError: Cannot read property '_createAttribute' of undefined
    at exports.clone (example-app\node_modules\jsdom\lib\jsdom\living\node.js:40:23)
    at AttrImpl.cloneNode (example-app\node_modules\jsdom\lib\jsdom\living\nodes\Node-impl.js:498:12)
    at Attr.cloneNode (example-app\node_modules\jsdom\lib\jsdom\living\generated\Node.js:143:49)
    at about:blank:2:61
    at Script.runInContext (vm.js:137:20)
    at Object.runInContext (vm.js:300:6)
    at processJavaScript (example-app\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:241:10)
    at HTMLScriptElementImpl._innerEval (example-app\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:168:5)
    at example-app\node_modules\jsdom\lib\jsdom\living\nodes\HTMLScriptElement-impl.js:107:12
    at ResourceQueue.push (example-app\node_modules\jsdom\lib\jsdom\browser\resources\resource-queue.js:53:16)

```

https://github.com/jsdom/jsdom/blob/b4b5a542380316a0d7296f7f41a5909bf5e097db/lib/jsdom/living/node.js#L40
`node._ownerDocument` may be `undefined` for Attribute node.
I use this to solve this problem for the moment.
```javascript
window.Attr.prototype.cloneNode = function cloneNode () {
  const attr = window.document.createAttribute(this.name)
  attr.value = this.value
  return attr
}
```

**Comment by TimothyGu** [comment]
Can you check if https://github.com/jsdom/jsdom/pull/2820 fixes it? I suspect it would.

**Comment by lovetingyuan** [comment]
I use your branch `TimothyGu/jsdom/tree/attr-bug`, there is no error when running the case above.
