### ISSUE TITLE
jsdom returns integer instead of timer object for timer functions

### ISSUE THREAD

**Issue by retrohacker** [jsdom/jsdom#2990]
### Basic info:

- **Node.js version:** 12.16.0
- **jsdom version:** 16.2.2

https://nodejs.org/api/timers.html

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
new JSDOM(`<body><script>setInterval(() => console.log("hai"), 1000).unref();`, { runScripts: "dangerously" });
```

*Expected Result*

```
$ node index.js
```

*Actual Result*

```
$ node index.js
Error: Uncaught [TypeError: setInterval(...).unref is not a function]
    at reportException (/home/retrohacker/Development/deleteme/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
    at processJavaScript (/home/retrohacker/Development/deleteme/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:243:7)
    at HTMLScriptElementImpl._innerEval (/home/retrohacker/Development/deleteme/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:176:5)
    at /home/retrohacker/Development/deleteme/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:115:12
    at ResourceQueue.push (/home/retrohacker/Development/deleteme/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:53:16)
    at HTMLScriptElementImpl._fetchInternalScript (/home/retrohacker/Development/deleteme/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:114:21)
    at HTMLScriptElementImpl._eval (/home/retrohacker/Development/deleteme/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:170:12)
    at HTMLScriptElementImpl._poppedOffStackOfOpenElements (/home/retrohacker/Development/deleteme/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:133:10)
    at OpenElementStack.pop (/home/retrohacker/Development/deleteme/node_modules/jsdom/lib/jsdom/browser/parser/html.js:43:12)
    at Object.eofInText [as EOF_TOKEN] (/home/retrohacker/Development/deleteme/node_modules/parse5/lib/parser/index.js:2159:20) TypeError: setInterval(...).unref is not a function
    at about:blank:1:45
    at Script.runInContext (vm.js:131:20)
    at Object.runInContext (vm.js:295:6)
    at processJavaScript (/home/retrohacker/Development/deleteme/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:241:10)
    at HTMLScriptElementImpl._innerEval (/home/retrohacker/Development/deleteme/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:176:5)
    at /home/retrohacker/Development/deleteme/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:115:12
    at ResourceQueue.push (/home/retrohacker/Development/deleteme/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:53:16)
    at HTMLScriptElementImpl._fetchInternalScript (/home/retrohacker/Development/deleteme/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:114:21)
    at HTMLScriptElementImpl._eval (/home/retrohacker/Development/deleteme/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:170:12)
    at HTMLScriptElementImpl._poppedOffStackOfOpenElements (/home/retrohacker/Development/deleteme/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:133:10)
hai
hai
hai
hai
...
```

### How does similar code behave in browsers?

No idea, I came here because jest seems to be running server side tests with jsdom.

**Comment by domenic** [comment]
This is working as intended. The code `setInterval(() => console.log("hai"), 1000).unref()` in browsers throws the same error. jsdom emulates a browser.

**Comment by retrohacker** [comment]
Thanks for the context, sorry for the noise.

**Comment by retrohacker** [comment]
For future travelers who end up here, jest uses jsdom by default. You can change this by setting `testEnvironment` to `node` as documented here: https://jestjs.io/docs/en/configuration.html#testenvironment-string
