### ISSUE TITLE
Warning about getComputedStyle with second argument is noisy

### ISSUE THREAD

**Issue by eps1lon** [jsdom/jsdom#3025]
### Basic info:

- **Node.js version:** 10.14
- **jsdom version:** 16.4.0

### Minimal reproduction case

any access to `getComputedStyle(element, pseudo)`

### How does similar code behave in browsers?

I don't know. Do they actually warn if an argument is passed that they can't handle?

As far as I understood it this warning is added because people could accidentally read the wrong styles. However, certain CSS properties only apply to certain pseudo elements and are therefore safe to read e.g. `content` ( `window.getComputedStyle(document.body, ':after').getPropertyValue('content')`). Since `document.body` cannot have a `content` CSS property I will never read the wrong value. Only no value which is a degrades gracefully since that is what you'd expect if it isn't supported. Adding a warning is not graceful.

This warning made `dom-accessibility-api` unusable in JSDOM due to the generated noise. 

If you saw people using it wrongly then we should probably move the warning to the getters in the returned `CSSStyleDeclaration`.

**Comment by p1t1ch** [comment]
I'm not using `getComputedStyle` directly, but after dependencies update on project, which uses Jest, my test suites are still passed, but the whole console is red with tens of `Not implemented: window.computedStyle(elt, pseudoElt)` warnings. I had to lock `jsdom` version to `16.3.0` with `resolutions` field for now 😕

**Comment by domenic** [comment]
I'm not opposed to reverting this, but I'd like to understand more.

`document.body` can totally have a `content` CSS property, by the way, and you will get the wrong value (i.e., the body element's value, instead of that of `body::after`) in jsdom for `getComputedStyle(document.body, "::after")`.

So... people are using `getComputedStyle()`, and passing a pseudo-element, but... OK with getting totally wrong data, that is actually the data for the non-pseudo element? That seems really, really bad?

I think a warning in these cases would make a lot more sense. If I could find some way to prevent people from calling getComputedStyle() at all in these cases, that would be even better. (This goes for all unimplemented-in-jsdom features.)

Perhaps throwing an exception would be more helpful, since it would immediately crash the program instead of repeatedly warning? In particular I think it'd be much better to surface the bug in the calling code, instead of silently hiding it like previous versions of jsdom did.

**Comment by eps1lon** [comment]
> document.body can totally have a content CSS property, by the way, and you will get the wrong value (i.e., the body element's value, instead of that of body::after) in jsdom for getComputedStyle(document.body, "::after").

In what browsers though? According to MDN [`content` is only supported on pseudo elements](https://developer.mozilla.org/en-US/docs/Web/CSS/content). Though the [latest css-content editors draft marks says it's supported on every element](https://drafts.csswg.org/css-content-3/#content-property).

So it seems like `content` is only supported on normal elements in newer browsers which also implement the second argument of getComputedStyles. Therefore I cannot read a wrong value in a browser. JSDOM might be the exception if you start supporting `content` on normal elements but don't support the second argument of `getComputedStyle`. Now I could start sniffing the user-agent but, if I remember correctly, that one can be overridden by users.

> Perhaps throwing an exception would be more helpful, since it would immediately crash the program instead of repeatedly warning? 

That would help my specific case more since it requires less code compared to mocking console.error, reading the warning and then issuing it again if it doesn't concern me which messes up stacktraces.

**Comment by domenic** [comment]
I'm not sure what you mean by "supported on every element" vs. "supported on pseudo elements". I agree browsers don't *render* the content property on non-pseudos yet. But both they and jsdom do *support* it: https://jsbin.com/yiqofiquca/edit?html,console,output.

So in particular, the bug I'm worried about here is pages like the above, where `getComputedStyle(document.body, "::after").content` will return `"foo"` in jsdom, but `none` in browsers.

You can also use https://github.com/jsdom/jsdom#virtual-consoles to check for not-implemented errors.

**Comment by eps1lon** [comment]
> I'm not sure what you mean by "supported on every element" vs. "supported on pseudo elements".

The `content` value is empty on unsupported elements

> So in particular, the bug I'm worried about here is pages like the above, where getComputedStyle(document.body, "::after").content will return "foo" in jsdom, but none in browsers.

I'm fine with this bug. It seems highly unlikely to appear in actual applications. I'd rather have one silent bug than a million false positives warning which is probably a fair estimate.

> You can also use jsdom/jsdom#virtual-consoles to check for not-implemented errors.

This is not viable for a library.

Either way, since neither console error nor thrown error are spec compliant I'd rather catch an error than deal with mocked console.error stacktraces.

**Comment by domenic** [comment]
> The content value is empty on unsupported elements

That is not true in browsers, as you can see from the test case I linked.

**Comment by eps1lon** [comment]
It's empty in browsers that don't implement the second argument which is what we're talking about.

**Comment by eps1lon** [comment]
How is a library supposed to use `getComputedStyle` that works for browsers and JSDOM? If a browser doesn't support a specific property then the value would return nonsense. This was and will always be the case. Only in JSDOM do you get warnings. The problem is that these warnings aren't actionable which renders them as noise. 

Would a thrown error work for you?

**Comment by domenic** [comment]
> It's empty in browsers that don't implement the second argument which is what we're talking about.

I'm not aware of any browsers of that sort. That's what makes this such a difficult problem; we don't have any browsers to emulate, so we will give misleading results for anyone trying to use it. Thus, we warn them about misleading results.

> How is a library supposed to use getComputedStyle that works for browsers and JSDOM?

Don't use the second argument. In general, if a library wants to work in multiple environments, it needs to confine itself to the supported intersection features of those environments.

> If a browser doesn't support a specific property then the value would return nonsense. This was and will always be the case. Only in JSDOM do you get warnings

This is not about properties. Neither jsdom nor browsers have any special treatment for different properties here. This is about arguments.

> The problem is that these warnings aren't actionable which renders them as noise.

They are actionable. Don't use the second argument.

**Comment by eps1lon** [comment]
> They are actionable. Don't use the second argument.

So I can't write a library that works in JSDOM and the browser?

**Comment by domenic** [comment]
Not if you want to compute the style of pseudo-elements, no! jsdom doesn't support doing so, so there's no way that such a library would work.

**Comment by domenic** [comment]
I don't understand what "constructed edge case" you're talking about. This whole thread is literally about the second argument to getComputedStyle. If you're calling that an edge case not worth arguing about, then why even open the issue?

**Comment by eps1lon** [comment]
The edge case is the one you constructed that returns a wrong value. My contention is that the amount of warnings stands in no relation to the issues it uncovers. If 99% of warnings are false positives then they are meaningless.

**Comment by domenic** [comment]
Any time you use the second argument, you are going to get a different value between jsdom and browsers. Sure, you can construct edge cases where both the pseudo-element and the main element have the same value, but you can also construct edge cases where `document.body` has the same CSS values as `document.head`. That doesn't justify jsdom giving you computed styles for `document.head` when you ask it for `document.body`'s computed styles.

**Comment by eps1lon** [comment]
So why would warning on the getter not work? I already conceded the point about properties other than `content`. I'm trying to find an actionable compromise while you are ignoring the concessions I make. I don't see you arguing in good faith but rather attacking the weakest point. I'm opting out of this discussion since you don't seem to be willing to create a usable solution. I hope this warning adds value for someone.

**Comment by domenic** [comment]
Indeed, I think I'll also opt out of this discussion; the last few messages have gotten particularly hurtful and this isn't how I want to spend my open source time.

**Comment by linonetwo** [comment]
Hi I get

```
stderr | src/pages/Main/__tests__/index.test.tsx > Main Page > should switch to Agent page content when clicking Agent workspace       
Error: Not implemented: window.getComputedStyle(elt, pseudoElt)
    at module.exports (C:\Users\linonetwo\Documents\repo-c\TidGi-Desktop\node_modules\jsdom\lib\jsdom\browser\not-implemented.js:9:17) 
    at window.getComputedStyle (C:\Users\linonetwo\Documents\repo-c\TidGi-Desktop\node_modules\jsdom\lib\jsdom\browser\Window.js:895:7)
    at SimpleBarCore.getScrollbarWidth (C:\Users\linonetwo\Documents\repo-c\TidGi-Desktop\node_modules\simplebar-core\src\index.ts:266:11)
    at SimpleBarCore.init (C:\Users\linonetwo\Documents\repo-c\TidGi-Desktop\node_modules\simplebar-core\src\index.ts:301:34)
    at new SimpleBarCore (C:\Users\linonetwo\Documents\repo-c\TidGi-Desktop\node_modules\simplebar-core\src\index.ts:207:10)
    at C:\Users\linonetwo\Documents\repo-c\TidGi-Desktop\node_modules\index.tsx:70:20
    at Object.react-stack-bottom-frame (C:\Users\linonetwo\Documents\repo-c\TidGi-Desktop\node_modules\react-dom\cjs\react-dom-client.development.js:22509:20)
    at runWithFiberInDEV (C:\Users\linonetwo\Documents\repo-c\TidGi-Desktop\node_modules\react-dom\cjs\react-dom-client.development.js:543:16)
    at commitHookEffectListMount (C:\Users\linonetwo\Documents\repo-c\TidGi-Desktop\node_modules\react-dom\cjs\react-dom-client.development.js:10758:29)
    at commitHookPassiveMountEffects (C:\Users\linonetwo\Documents\repo-c\TidGi-Desktop\node_modules\react-dom\cjs\react-dom-client.development.js:10880:11)
    at commitPassiveMountOnFiber (C:\Users\linonetwo\Documents\repo-c\TidGi-Desktop\node_modules\react-dom\cjs\react-dom-client.development.js:12653:13)
    at recursivelyTraversePassiveMountEffects (C:\Users\linonetwo\Documents\repo-c\TidGi-Desktop\node_modules\react-dom\cjs\react-dom-client.development.js:12627:11)
    at commitPassiveMountOnFiber (C:\Users\linonetwo\Documents\repo-c\TidGi-Desktop\node_modules\react-dom\cjs\react-dom-client.development.js:12646:11)
    at recursivelyTraversePassiveMountEffects (C:\Users\linonetwo\Documents\repo-c\TidGi-Desktop\node_modules\react-dom\cjs\react-dom-client.development.js:12627:11)
    at commitPassiveMountOnFiber (C:\Users\linonetwo\Documents\repo-c\TidGi-Desktop\node_modules\react-dom\cjs\react-dom-client.development.js:12646:11)
    at recursivelyTraversePassiveMountEffects (C:\Users\linonetwo\Documents\repo-c\TidGi-Desktop\node_modules\react-dom\cjs\react-dom-client.development.js:12627:11) undefined
```

How to disable this warning? It is from a depencdency, but I don't want to touch it.


---

```ts
import { configure } from '@testing-library/dom';
import { BehaviorSubject } from 'rxjs';
import { afterAll, vi } from 'vitest';

configure({
  computedStyleSupportsPseudoElements: false,
});
```

This is not working anymore ↑ https://github.com/testing-library/dom-testing-library/issues/774#issuecomment-2973976293

---

workaround:

https://github.com/NickColley/jest-axe/issues/147#issuecomment-758804533
