### ISSUE TITLE
Error: Uncaught [TypeError: Failed to execute 'addRange' on 'Selection': parameter 1 is not of type 'Range'.]

### ISSUE THREAD

**Issue by sibelius** [jsdom/jsdom#3036]
### Basic info:

- **Node.js version:**  v12.18.0
- **jsdom version:** jsdom@16.4.0
- draft-js@0.11.5

### Minimal reproduction case

```js
Error: Uncaught [TypeError: Failed to execute 'addRange' on 'Selection': parameter 1 is not of type 'Range'.]
at reportException (app/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
at innerInvokeEventListeners (app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:333:9)
at invokeEventListeners (app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
at HTMLUnknownElementImpl._dispatch (app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
at HTMLUnknownElementImpl.dispatchEvent (app/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
at HTMLUnknownElement.dispatchEvent (app/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
at Object.invokeGuardedCallbackDev (app/node_modules/react-dom/cjs/react-dom.development.js:237:16)
at invokeGuardedCallback (app/node_modules/react-dom/cjs/react-dom.development.js:292:31)
at commitRootImpl (app/node_modules/react-dom/cjs/react-dom.development.js:22541:9)
at unstable_runWithPriority (app/node_modules/scheduler/cjs/scheduler.development.js:653:12) TypeError: Failed to execute 'addRange' on 'Selection': parameter 1 is not of type 'Range'.
  at Object.exports.convert (app/node_modules/jsdom/lib/jsdom/living/generated/Range.js:25:9)
at Selection.addRange (app/node_modules/jsdom/lib/jsdom/living/generated/Selection.js:134:24)
at addPointToSelection (app/node_modules/draft-js/lib/setDraftEditorSelection.js:285:15)
at setDraftEditorSelection (app/node_modules/draft-js/lib/setDraftEditorSelection.js:136:5)
at DraftEditorLeaf._setSelection (app/node_modules/draft-js/lib/DraftEditorLeaf.react.js:97:5)
at DraftEditorLeaf.componentDidUpdate (app/node_modules/draft-js/lib/DraftEditorLeaf.react.js:108:10)
```

### How does similar code behave in browsers?

it works

---

This bugs happens on a Draft Editor test using testing library

I've get the text input like this:

```jsx
const bodyInput = getByTestId('body');
```

I try to update the content editable like this:

```jsx
const body = 'postDraftBody';
contentEditableChange(bodyInput, body);
```

```jsx
import { createEvent } from '@testing-library/dom';
import { fireEvent } from '@testing-library/react';

export const createPasteEvent = (html: string) => {
  const text = html.replace('<[^>]*>', '');
  return {
    clipboardData: {
      types: ['text/plain', 'text/html'],
      getData: (type) => (type === 'text/plain' ? text : html),
    },
  };
};


export const contentEditableChange = (node, value) => {
  const eventProperties = createPasteEvent(value);
  const pasteEvent = createEvent.paste(node, eventProperties);

  fireEvent(node, pasteEvent); 
};
```

**Comment by sibelius** [comment]
I've got an old `createRange` mock that was broken
