### ISSUE TITLE
Valid CSS selector crashes JSDOM but not browser

### ISSUE THREAD

**Issue by vedantroy** [jsdom/jsdom#3057]
### Basic info:

- **Node.js version:** 12.18.1
- **jsdom version:** 16.4.0

### Minimal reproduction case

(Download test.html.txt & rename it to test.html)

[test.html.txt](https://github.com/jsdom/jsdom/files/5294438/test.html.txt)

```js
const fs = require('fs')
const { JSDOM } = require('jsdom')
const file = fs.readFileSync('./test.html')
const dom = new JSDOM(file)
const el = dom.window.document.querySelector('.team-wrap .clearfix:nth-of-type(1) tr:nth-of-type(2) .u-hyphenate')
```

throws the following exception:

```
undefined:1
"use strict";return function Resolver(c,f,x,r){var e,n,o,j=r.length-1,k=-1;main:while((e=c[++k])){n=e;while((e=e.parentElement)){n=s.nthOfType(e,false);if((n==2)){if((e.nodeName.toLowerCase()=="tr")){n=e;while((e=e.parentElement)){n=e;o=e.nodeName;while((n=n.previousElementSibling)&&n.nodeName!=o);if(!n){if((/(^|\s)clearfix(\s|$)/.test(e.getAttribute("class")))){n=e;while((e=e.parentElement)){if((/(^|\s)team-wrap(\s|$)/.test(e.getAttribute("class")))){r[++j]=c[k];continue main;}}e=n;}}}e=n;}}}e=n;}s.nthOfType(null, 2);return r;}
                                                                                                                 ^

TypeError: Cannot read property 'parentElement' of null
    at Array.Resolver (eval at compile (/home/vedantroy/Desktop/clay/jsdom-test/node_modules/nwsapi/src/nwsapi.js:768:17), <anonymous>:1:114)
    at collect (/home/vedantroy/Desktop/clay/jsdom-test/node_modules/nwsapi/src/nwsapi.js:1556:23)
    at _querySelectorAll (/home/vedantroy/Desktop/clay/jsdom-test/node_modules/nwsapi/src/nwsapi.js:1518:36)
    at Object._querySelector [as first] (/home/vedantroy/Desktop/clay/jsdom-test/node_modules/nwsapi/src/nwsapi.js:1424:14)
    at DocumentImpl.querySelector (/home/vedantroy/Desktop/clay/jsdom-test/node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:63:44)
    at Document.querySelector (/home/vedantroy/Desktop/clay/jsdom-test/node_modules/jsdom/lib/jsdom/living/generated/Document.js:939:58)
    at Object.<anonymous> (/home/vedantroy/Desktop/clay/jsdom-test/run.js:9:32)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
```

### How does similar code behave in browsers?

In browsers, the selector returns an HTML element.

Reproduction: https://repl.it/@VedRoy/GlossyRedCareware

You can verify this works in the browser by opening the HTML file in chrome and pasting in `window.document.querySelector('.team-wrap .clearfix:nth-of-type(1) tr:nth-of-type(2) .u-hyphenate')`, it will return an HTML element.

**Comment by ArnaudBuchholz** [comment]
Got the same issue, had to work around to ensure that the function named `matchesDontThrow` actually does not throw ;-)
https://github.com/ArnaudBuchholz/ui5-test-runner/blob/main/src/defaults/jsdom/compatibility.js#L51
