### ISSUE TITLE
load jsdom error

### ISSUE THREAD

**Issue by 126217832** [jsdom/jsdom#3071]
***************error start********************
/data/wwwroot/spider/node_modules/jsdom/lib/api.js:147
  static async fromFile(filename, options = {}) {
               ^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/data/wwwroot/spider/t.js:1:77)

***************error end********************

The environment is in centos7

**Comment by domenic** [comment]
This issue does not follow the issue template, and as such will be closed.
