### ISSUE TITLE
TypeError: performance.getEntriesByType is not a function while executing the test

### ISSUE THREAD

**Issue by slim-hmidi** [jsdom/jsdom#3122]
### Basic info:

- **Node.js version:**  14.5.5
- **jsdom version:**  16.4.0

### Minimal reproduction case

```ts
import React, {useCallback, useEffect} from 'react';
import {Redirect, RouteComponentProps, Route } from 'react-router-dom';


interface Props {
  component: React.FC<any>;
  render?: (props: RouteComponentProps<any>) => React.ReactNode;
  path: string;
  role: string;
  redirectionPath?: string;
}

const RefreshRoute = ({
  component: Component,
  redirectionPath,
  ...rest
}: Props): JSX.Element => {
  redirectionPath = redirectionPath ?? '/';
  const perf = performance.getEntriesByType('navigation')[0].toJSON();
  const reloadType = perf.type !== 'reload';

  const handler = useCallback((e) => {
    e.preventDefault();
    e.returnValue = '';
    return true;
  }, []);

  useEffect(() => {
    window.onbeforeunload = handler;

    return () => {
      window.onbeforeunload = handler;
    };
  }, [handler]);
  return (
    <>
      {reloadType ? (
        <Route component={Component} {...rest} />
      ) : (
        <Redirect to={redirectionPath} />
      )}
    </>
  );
};
export default RefreshRoute;
```

RefereshRoute.tsx:
```ts
import React from 'react';
import {render} from '@testing-library/react';
import {screen} from '@testing-library/dom';
import {MemoryRouter} from 'react-router-dom';
import App from '../App';

describe('RefreshRoute', () => {
  test('Should render the component successfully in the first render', () => {
    render(
      <MemoryRouter
        initialEntries={['/', '/refs', '/refs/create', '/lib']}
        initialIndex={2}
      >
        <App />
      </MemoryRouter>,
      {},
    );

    expect(screen.getByLabelText(/creation/)).toBeInTheDocument();
  });
});
````

I got this error: 
```
TypeError: performance.getEntriesByType is not a function

      17 | }: Props): JSX.Element => {
      18 |   redirectionPath = redirectionPath ?? '/';
    > 19 |   const perf = performance.getEntriesByType('navigation')[0].toJSON();
         |                            ^
      20 |   const reloadType = perf.type !== 'reload';
      21 | 
      22 |   const handler = useCallback((e) => {

      at RefreshRoute (src/app/routes/RefreshRoute.tsx:19:28)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17811:13)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19049:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23964:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22779:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22707:5)
      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:22670:7)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22293:18)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:25482:3)
      at node_modules/react-dom/cjs/react-dom.development.js:26021:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:22431:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:26020:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:26103:10)
      at node_modules/@testing-library/react/dist/pure.js:99:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22380:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at render (node_modules/@testing-library/react/dist/pure.js:95:26)
      at render (src/test/CustomRender.tsx:47:10)
      at Object.<anonymous> (src/app/routes/RefreshRoute.test.tsx:8:5)
      
```
Seems like `performance.getEntriesByType`  does not exist.
### How does similar code behave in browsers?

(Link to a jsbin or similar strongly suggested.)

**Comment by domenic** [comment]
This appears to use a non-JavaScript language and so does not qualify as a minimal example.

**Comment by slim-hmidi** [comment]
Not clear your comment.btw I used jest to mock the component until it will be taken into consideration for the test in the next versions.
