### ISSUE TITLE
JSDOM error when emulate pages (reading 'loadEventEnd')

### ISSUE THREAD

**Issue by spamator12** [jsdom/jsdom#3343]
### Basic info:

node: v16.13.0
jsdom: v16.6.0

just try to get any page via JSDOM:

```
Error: Uncaught [TypeError: Cannot read properties of undefined (reading 'loadEventEnd')]
    at reportException (X/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
    at processJavaScript (X/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:243:7)
    at HTMLScriptElementImpl._innerEval (X/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:176:5)
    at onLoadExternalScript (X/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:98:12)
    at onLoadWrapped (X/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:53:33)
    at Object.check (X/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:76:23)
    at X/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:119:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5) TypeError: Cannot read properties of undefined (reading 'loadEventEnd')
    at a.plugin (https://connect.facebook.net/signals/config/173202906590003?v=2.9.52&r=stable:26:44997)
    at b.value (https://connect.facebook.net/en_US/fbevents.js:24:52354)
    at Function.a.registerPlugin (https://connect.facebook.net/en_US/fbevents.js:27:12023)
    at https://connect.facebook.net/signals/config/173202906590003?v=2.9.52&r=stable:26:45739
    at https://connect.facebook.net/signals/config/173202906590003?v=2.9.52&r=stable:26:45879
    at https://connect.facebook.net/signals/config/173202906590003?v=2.9.52&r=stable:26:45883
    at Script.runInContext (node:vm:139:12)
    at Object.runInContext (node:vm:289:6)
    at processJavaScript (X/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:241:10)
    at HTMLScriptElementImpl._innerEval (X/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:176:5)
```

any idea how to fix this? It happended when I update JSDOM to v16.6.0, but on test it seems to NOT work even on v19. Thanks for any thoughts on this.

**Comment by domenic** [comment]
Not enough info to reproduce.
