### ISSUE TITLE
jsdom + rollup fail!

### ISSUE THREAD

**Issue by hzmnet** [jsdom/jsdom#3356]
### Basic info:

- **Node.js version:** newest
- **jsdom version:** newest

### Minimal reproduction case

index.js
```
const { JSDOM } = require("jsdom");

```

### How does similar code behave in browsers?

(Link to a jsbin or similar strongly suggested.)

````
./index.js → dist/js/main.min.js...
(!) Plugin node-resolve: preferring built-in module 'path' over local alternative at 'path', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
(!) Plugin node-resolve: preferring built-in module 'fs' over local alternative at 'fs', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
(!) Plugin node-resolve: preferring built-in module 'events' over local alternative at 'events', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
(!) Plugin node-resolve: preferring built-in module 'url' over local alternative at 'url', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
[!] (plugin commonjs) TypeError: Cannot read properties of undefined (reading 'type')
../../../../../../node_modules/domexception/webidl2js-wrapper.js
TypeError: Cannot read properties of undefined (reading 'type')
    at /Users/shadow/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:532:43
    at Array.forEach (<anonymous>)
    at Object.enter (/Users/shadow/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:531:40)
    at visit (/Users/shadow/node_modules/estree-walker/dist/estree-walker.umd.js:28:10)
    at visit (/Users/shadow/node_modules/estree-walker/dist/estree-walker.umd.js:50:5)
    at visit (/Users/shadow/node_modules/estree-walker/dist/estree-walker.umd.js:45:35)
    at Object.walk (/Users/shadow/node_modules/estree-walker/dist/estree-walker.umd.js:8:3)
    at transformCommonjs (/Users/shadow/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:433:16)
    at Object.transformAndCheckExports (/Users/shadow/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:779:27)
    at Object.transform (/Users/shadow/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:842:48)
````

**Comment by domenic** [comment]
Yep, Rollup is not supported; this is a Node.js module.

**Comment by nafg** [comment]
And Rollup can handle Node.js modules, as well as output them.
