### ISSUE TITLE
Getting `read of undefined (reading _customElementDefinitions)` error when import React components from our private lib

### ISSUE THREAD

**Issue by elfiservice** [jsdom/jsdom#3378]
Firstly, I just would like some advice or support about that

### Basic info:

- **Node.js version: 16.14**
- **jsdom version: 19**
- jest version: **28.1**

### Minimal reproduction case
When I execute my test that have my import of my react component lib i Get This Error bellow
NOTE: this lib use `Onsenui` lib

```js

  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading '_customElementDefinitions')

      at lookupCEDefinition (node_modules/jsdom/lib/jsdom/living/helpers/custom-elements.js:154:37)
      at JSDOMParse5Adapter.createElement (node_modules/jsdom/lib/jsdom/browser/parser/html.js:92:24)
      at Parser.parseFragment (node_modules/jsdom/node_modules/parse5/lib/parser/index.js:359:47)
      at Object.parseFragment (node_modules/jsdom/node_modules/parse5/lib/index.js:22:19)
      at parseFragment (node_modules/jsdom/lib/jsdom/browser/parser/html.js:209:17)
      at parseFragment (node_modules/jsdom/lib/jsdom/browser/parser/index.js:18:10)
      at HTMLBodyElementImpl.set innerHTML [as innerHTML] (node_modules/jsdom/lib/jsdom/living/domparsing/InnerHTML-impl.js:20:22)
      at HTMLBodyElement.set innerHTML (node_modules/jsdom/lib/jsdom/living/generated/Element.js:1538:42)
      at HTMLBodyElement.call [as innerHTML] (node_modules/node_modules/@onsenui/custom-elements/src/Patch/Element.js:54:28)
      at Window.close (node_modules/jsdom/lib/jsdom/browser/Window.js:760:39)

```
- I debugged in this file `custom-elements.js` and I saw that this `registry` bellow var some time get `undefined` 

```
...

  const registry = implForWrapper(document._globalObject.customElements);

  const definitionByName = registry._customElementDefinitions.find(def => {
    return def.name === def.localName && def.localName === localName;
  });
  if (definitionByName !== undefined) {
    return definitionByName;
  }

  const definitionByIs = registry._customElementDefinitions.find(def => {
    return def.name === isValue && def.localName === localName;
  });
  if (definitionByIs !== undefined) {
    return definitionByIs;
  }

...

```

Tks 🙏🏽

**Comment by domenic** [comment]
Sorry, it looks like you are using a third-party library (Jest), and as such this is not a bug we can help with. The issue template requires reproduction code that we can run on our own computers, with no dependencies installed except jsdom.

**Comment by henrykuijpers** [comment]
@elfiservice  I have the same error, when I try to import the https://github.com/adobe/coral-spectrum components, I get the same error as you have. I'm also using JEST, just like you. Did you come up with a solution for this problem? 

Apparently, indeed, the `registry`-variable becomes `undefined`, which leads to this error.

**Comment by elfiservice** [comment]
hi @henrykuijpers  
- I figured out that this is due the OnsenUi library (in my case)
  - this lib have your own "HMTL" tags like `<ons-side-menu>` so, they have Custom elements
- Thus `Jsdom does not recognises them  

I think the solution would be make Mock this custom elements in someway

So, I just keep using the Karma Js to test my React components using OnsenUi 
I gave up using Jsdom to simulate the DOM changes
