### ISSUE TITLE
JSDOM cannot parse css `clip: rect()`

### ISSUE THREAD

**Issue by hasezoey** [jsdom/jsdom#3400]
### Basic info:

- **Node.js version:** 18.3.0
- **jsdom version:** 20.0.0

### Minimal reproduction case

```js
const html = "<html><head><style>{ clip: rect(1px, 1px, 1px, 1px); }</style></head><body></body></html>";

new jsdom.JSDOM(html);
```

Error:

```txt
Error: Could not parse CSS stylesheet
    at exports.createStylesheet (/mnt/projects/nodejs/scraper/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:34:21)
    at HTMLStyleElementImpl._updateAStyleBlock (/mnt/projects/nodejs/scraper/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:68:5)
    at HTMLStyleElementImpl._poppedOffStackOfOpenElements (/mnt/projects/nodejs/scraper/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:42:10)
    at JSDOMParse5Adapter.onItemPop (/mnt/projects/nodejs/scraper/node_modules/jsdom/lib/jsdom/browser/parser/html.js:175:43)
    at Parser.onItemPop (/mnt/projects/nodejs/scraper/node_modules/parse5/dist/cjs/parser/index.js:158:90)
    at OpenElementStack.pop (/mnt/projects/nodejs/scraper/node_modules/parse5/dist/cjs/parser/open-element-stack.js:89:22)
    at endTagInText (/mnt/projects/nodejs/scraper/node_modules/parse5/dist/cjs/parser/index.js:2180:20)
    at Parser._endTagOutsideForeignContent (/mnt/projects/nodejs/scraper/node_modules/parse5/dist/cjs/parser/index.js:858:17)
    at Parser.onEndTag (/mnt/projects/nodejs/scraper/node_modules/parse5/dist/cjs/parser/index.js:831:18)
    at Tokenizer.emitCurrentTagToken (/mnt/projects/nodejs/scraper/node_modules/parse5/dist/cjs/tokenizer/index.js:403:26) 
```

### How does similar code behave in browsers?

just works in firefox (102) from what i can tell

**Comment by yepitschunked** [comment]
You forgot to add a selector to your CSS.

**Comment by hasezoey** [comment]
i dont know what i wanted to achieve with that, but yes, now that i look at it again it looks like i was missing the selector (maybe some kind of better error would be great?)
