### ISSUE TITLE
Support `document.adoptedStyleSheets`

### ISSUE THREAD

**Issue by nnmax** [jsdom/jsdom#3444]
### Basic info:

- **Node.js version: 16.17.0**
- **jsdom version: 20.0.0**

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom')

const dom = new JSDOM(`
  <div>foo</div>
`)

console.log(dom.window.document.adoptedStyleSheets) // `undefined`
```
[adoptedStyleSheets API](https://developer.mozilla.org/en-US/docs/Web/API/Document/adoptedStyleSheets)

### How does similar code behave in browsers?

(Link to a jsbin or similar strongly suggested.)

**Comment by nnmax** [comment]
Do you have any ideas for supporting this API? I'd be happy to submit a PR for support if I could.

**Comment by domenic** [comment]
I'd suggest implementing it, according to its specification.

**Comment by nnmax** [comment]
I need to write tests for my custom components. My custom components use both APIs and reports errors when I run the tests.

**Custom components:**

```TypeScript
export default class Button extends HTMLElement {
  static formAssociated = true

  #internals: ElementInternals

  constructor() {
    super()
    this.attachShadow({ mode: 'open' })
    this.shadowRoot.adoptedStyleSheets.push(styles)
    this.#internals = this.attachInternals()
  }

  // ...some code...

  #render() {
    this.shadowRoot.innerHTML = `
      <button tabindex="-1">
        <slot></slot>
        <max-ripple></max-ripple>
      </button>
    `
  }
}
```

**Test file:**

```TypeScript
describe('Testing <max-button />', () => {
  it('custom elements should be defined', () => {
    const button = window.customElements.get('max-button')
    expect(button).toBeDefined()
  })

  // TODO: await for JSDOM support `HTMLElement.attachInternals()` API
  // https://github.com/jsdom/jsdom/issues/3444
  it.skip.each([
    { attribute: 'variant', value: 'contained' },
    { attribute: 'variant', value: 'outlined' },
    { attribute: 'variant', value: 'text' },
    { attribute: 'color', value: 'primary' },
    { attribute: 'color', value: 'secondary' },
    { attribute: 'type', value: 'button' },
    { attribute: 'type', value: 'submit' },
    { attribute: 'type', value: 'reset' },
    { attribute: 'disabled', value: '' },
    { attribute: 'role', value: 'menuitem' },
    { attribute: 'tabindex', value: '-1' },
  ])('should render a button with $attribute is `$value`', ({ attribute, value }) => {
    document.body.innerHTML = `
      <max-button ${attribute}="${value}">Button</max-button>
    `

    expect(document.body.innerHTML).toMatchSnapshot()
  })
})
```

**Output:**

```text
  ● Testing <max-button /> › should render a button with role is `menuitem`

    TypeError: _this.attachInternals is not a function

      14 |     this.attachShadow({ mode: 'open' })
      15 |     this.shadowRoot.adoptedStyleSheets = [styles]
    > 16 |     this.#internals = this.attachInternals()
         |                            ^
      17 |   }
      18 |
      19 |   get #rippleRoot() {

      at new attachInternals (src/Button/Button.ts:16:28)
```

**Comment by iamallyniam** [comment]
Has there been any movement on this? I have a number of web components that are using declarative shadow dom but can't run them in tests because attachInternals isn't supported.

**Comment by cscheffauer** [comment]
+1

**Comment by maciej-klemarczyk-se** [comment]
I have issues with this in library that is derived from Stencil. Is it okay to submit partial implementation ?
I would like to contribute in a way that unit tests can pass with that library.

I get errors similar to that one below coming from code : https://github.com/stenciljs/core/blob/3771af0aaed0dee078beb2fa4639d21668dabf00/src/runtime/styles.ts#L180
```
  console.error
    TypeError: Cannot read properties of undefined (reading 'includes')
        at addStyle (node_modules\stencilBasedUiLib\core\components\p-4zRD89V2.js:527:55)
        at attachStyles (node_modules\stencilBasedUiLib\core\components\p-4zRD89V2.js:542:20)
        at node_modules\stencilBasedUiLib\core\components\p-4zRD89V2.js:1634:5
        at Generator.next (<anonymous>)
        at node_modules\tslib\tslib.js:169:75
        at new ZoneAwarePromise (node_modules\zone.js\bundles\zone.umd.js:2196:37)
        at Object.__awaiter (node_modules\tslib\tslib.js:165:16)
        at updateComponent (node_modules\stencilBasedUiLib\core\components\p-4zRD89V2.js:1628:66)
        at node_modules\stencilBasedUiLib\core\components\p-4zRD89V2.js:1621:38
        at _ZoneDelegate.invoke (node_modules\zone.js\bundles\zone.umd.js:409:168)
        at _ZoneImpl.run (node_modules\zone.js\bundles\zone.umd.js:162:47)
        at node_modules\zone.js\bundles\zone.umd.js:2174:42
        at _ZoneDelegate.invokeTask (node_modules\zone.js\bundles\zone.umd.js:438:181)
        at _ZoneImpl.runTask (node_modules\zone.js\bundles\zone.umd.js:204:51)
        at drainMicroTaskQueue (node_modules\zone.js\bundles\zone.umd.js:615:39)

      at ../../node_modules/stencilBasedUiLib/core/components/p-4zRD89V2.js:1624:11
      at _ZoneDelegate.invoke (../../node_modules/zone.js/bundles/zone.umd.js:409:168)
      at _ZoneImpl.run (../../node_modules/zone.js/bundles/zone.umd.js:162:47)
      at ../../node_modules/zone.js/bundles/zone.umd.js:2174:42
      at _ZoneDelegate.invokeTask (../../node_modules/zone.js/bundles/zone.umd.js:438:181)
      at _ZoneImpl.runTask (../../node_modules/zone.js/bundles/zone.umd.js:204:51)
      at drainMicroTaskQueue (../../node_modules/zone.js/bundles/zone.umd.js:615:39)
```

**Comment by domenic** [comment]
No, jsdom does not accept partial implementations.
