### ISSUE TITLE
I have a question about an error I got from jsdom

### ISSUE THREAD

**Issue by DragosPV** [jsdom/jsdom#3468]
### Basic info:

- **Node.js version:** 18.12.1
- **jsdom version:** ^20.0.3

### Minimal reproduction case
```js
const { JSDOM } = require("jsdom");
const { window } = new JSDOM("");
const $ = require("jquery")(window);
$.ajax({
    url: `https://discordstatus.com/api/v2/incidents.json`,
    dataType: 'json',
    success: async function(data) {
        console.log(data)
    },
    error: async function(error) {
        console.error(error)
    }
});
```

### Question
So, I got this error from jsdom (as I can tell from the error itself):
```js
Error: getaddrinfo EAI_AGAIN discordstatus.com
    at Object.dispatchError (/bots/status-discord/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:63:19)
    at Request.<anonymous> (/bots/status-discord/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
    at Request.emit (node:events:525:35)
    at ClientRequest.<anonymous> (/bots/status-discord/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) undefined
```
I know that the error `getaddrinfo EAI_AGAIN` means internet problems, but what exactly made this error appear? And is it really internet problems that caused it?

**Comment by domenic** [comment]
Sorry, this issue does not contain enough information to reproduce the problem you're seeing. Please provide a full code sample which gives the error, and then we can help debug.

**Comment by DragosPV** [comment]
Oh, here you go

**Comment by DragosPV** [comment]
Nah, I think there is something really wrong with the server I'm hosting my code on, I got the same error on another code (a discord bot), is a little different than this one but the error message is the same:
```js
Error: getaddrinfo EAI_AGAIN discord.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'discord.com'
}
```
Besides these errors, on my discord bot sometimes it takes a lot of time to run some code, I mean it couldn't run 3 lines of code in 3 seconds, but I can't seem to convince the server's owner that there is a problem with the server, or maybe only with the container I have my code on (as he said I have a proxmox container, I don't really know much about this stuff), I thought you could help me with some answers about the first error so I could convince him to take action about these errors, but if you can't help me, I can understand.
