### ISSUE TITLE
Not implemented: HTMLCanvasElement.prototype.getContext

### ISSUE THREAD

**Issue by KarelJanVanHaute** [jsdom/jsdom#3568]
I'm trying to use jsdom with canvas on node v18.16.0

My package.json

```json
{
  "name": "paper_node_test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "canvas": "^2.11.2",
    "jsdom": "^22.1.0",
  }
}
```

My minimal test code

```js
var jsdom = require("jsdom");
const { JSDOM } = jsdom;

//draw something on the canvas with jsdom
const dom = new JSDOM(
  `<!DOCTYPE html><canvas id="canvas" width="400" height="400"></canvas>`
);
const canvas = dom.window.document.getElementById("canvas");
const ctx = canvas.getContext("2d");
ctx.fillStyle = "red";
ctx.fillRect(0, 0, 150, 75);
console.log(dom.window.document.documentElement.outerHTML);
```

The error I'm getting
```
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at HTMLCanvasElementImpl.getContext (/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
    at HTMLCanvasElement.getContext (/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:131:58)
    at Object.<anonymous> (/jsdom.js:10:20)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 undefined
/jsdom.js:11
ctx.fillStyle = "red";
              ^

TypeError: Cannot set properties of null (setting 'fillStyle')
    at Object.<anonymous> (/jsdom.js:11:15)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

**Comment by domenic** [comment]
After you run `npm install` and then `npm ls`, what is the output?

**Comment by KarelJanVanHaute** [comment]
├── canvas@2.11.2
└── jsdom@22.1.0

**Comment by domenic** [comment]
Well, something is off here, because when I paste in your example and try to run `npm install`, I get the following:

```
Could not parse project manifest
at /home/domenic/src/jsdom-test/package.json

Please ensure that the file is correctly formatted.
```

I'm wondering if you've actually tested the minimal reproduction case you've created...

**Comment by domenic** [comment]
OK. Well, I cannot reproduce that then; when I run the script I get

```
$ node index.js
<html><head></head><body><canvas id="canvas" width="400" height="400"></canvas></body></html>
```

**Comment by KarelJanVanHaute** [comment]
Very strange. And you ran it under the same conditions?
Node 18.16.0 on mac OSX 13.4?

**Comment by KarelJanVanHaute** [comment]
Ok this thing is driving me mad. When I tryed it on github codespaces I got the same error. I was installing everything with yarn. So I thought, maybe I try it again but I'll use npm instead. You never know. And it worked!!!
So to make a good case I retired it with a yarn install. And now that also works on codespaces. But when I try the same code locally I still get the error.

**Comment by KarelJanVanHaute** [comment]
Ok so when I spin up a new codespace on github and run the same code but now with npm, I get the same error.

**Comment by KarelJanVanHaute** [comment]
### Update:

For now, it seems to be a problem with node-canvas on a mac with a M1 processor. If you follow all their steps, I'm able to install canvas, but it performs a build on my machine. I'm guessing that's the problem. 
So jsdom does not seems to work with the arm64 version of canvas.

**Comment by KarelJanVanHaute** [comment]
For everyone here having the same problem. 
I've got it working. But to be honest, now idea how or what exactly fixed it. I uninstalled all the dependencies. And then reinstalled it.
`brew install pkg-config cairo pango libpng jpeg giflib librsvg`
I also did some updates of node-gyp. And all other stuff. 
### Some links I followed:
https://github.com/Automattic/node-canvas/issues/2251
https://github.com/nodejs/node-gyp/blob/main/docs/Force-npm-to-use-global-node-gyp.md
https://github.com/Automattic/node-canvas/issues/2036
https://github.com/nodejs/node-gyp/blob/main/docs/Updating-npm-bundled-node-gyp.md
