### ISSUE TITLE
Deploying failed due to JSDOM's module due to SyntaxError. 

### ISSUE THREAD

**Issue by 7adidaz** [jsdom/jsdom#3588]
### Basic info:

- **Node.js version:** v18.4.0
- **jsdom version:** 22.1.0

### Minimal reproduction case

```js
const jsdom = require('jsdom')

module.exports = async (url) => {
    try {
        let article = null;
        const res = await fetch(url);
        const text = await res.text();
        const dom = new jsdom.JSDOM(text);
        article = dom.window.document.querySelector('article').textContent;

        return article
    } catch (err) {
        return undefined;
    }
}
```

### How does similar code behave in browsers?
It's just a simple article tag extractor, the problem I'm facing is trying to deploy my application using render. 

NOTE: it works locally flawless. 

Render Deploying settings: 
- build command: npm install
- Start Command: npm start -> nodemon app.js

Deploying logs: 
``` bash
Aug 29 04:01:35 PM  /opt/render/project/src/server/node_modules/jsdom/lib/jsdom/living/nodes/HTMLInputElement-impl.js:583
Aug 29 04:01:35 PM        this[filesSymbol] ||= FileList.createImpl(this._globalObject);
Aug 29 04:01:35 PM                          ^^^
Aug 29 04:01:35 PM  
Aug 29 04:01:35 PM  SyntaxError: Unexpected token '||='
Aug 29 04:01:35 PM      at wrapSafe (internal/modules/cjs/loader.js:984:16)
Aug 29 04:01:35 PM      at Module._compile (internal/modules/cjs/loader.js:1032:27)
Aug 29 04:01:35 PM      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
Aug 29 04:01:35 PM      at Module.load (internal/modules/cjs/loader.js:933:32)
Aug 29 04:01:35 PM      at Function.Module._load (internal/modules/cjs/loader.js:774:14)
Aug 29 04:01:35 PM      at Module.require (internal/modules/cjs/loader.js:957:19)
Aug 29 04:01:35 PM      at require (internal/modules/cjs/helpers.js:88:18)
Aug 29 04:01:35 PM      at Object.<anonymous> (/opt/render/project/src/server/node_modules/jsdom/lib/jsdom/living/generated/HTMLInputElement.js:1875:14)
Aug 29 04:01:35 PM      at Module._compile (internal/modules/cjs/loader.js:1068:30)
Aug 29 04:01:35 PM      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
Aug 29 04:01:35 PM  [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by daavko** [comment]
[According to their docs](https://render.com/docs/node-version), Render uses Node 14.17.0 by default, which can also be seen in your log. The `||=` operator is only supported by Node 15 and up, so you'll have to specify a newer version. Preferably 16 or above, since jsdom seems to support only Node 16 and up.

**Comment by 7adidaz** [comment]
> [According to their docs](https://render.com/docs/node-version), Render uses Node 14.17.0 by default, which can also be seen in your log. The `||=` operator is only supported by Node 15 and up, so you'll have to specify a newer version. Preferably 16 or above, since jsdom seems to support only Node 16 and up.

thank you, i will switch back to jsdom and update the node module!
