### ISSUE TITLE
Getting memory leaks after running tests for a method that contains JSDOM

### ISSUE THREAD

**Issue by azakero** [jsdom/jsdom#3594]
### Basic info:

- **Node.js version:** v18.12.1
- **jsdom version:** v22.1.0

Sorry for not being able to add the code to reproduce the issue but added as much code as possible.

I have a class in a Nodejs app where I have a method that checks for malicious code in input value before storing in the database. The functionality is working perfectly fine but the issue arises when I try to test this method with some XSS vectors which I found online. The issue I am facing is memory leaks. 

This is the class with the method in question:

```
class Helper {

    static checkForXSS(string) {
       const dom               = new JSDOM(`<!DOCTYPE html><body></body>`),
       const DOMParser   = dom.window.DOMParser,
       const doc                = new DOMParser().parseFromString(string, 'text/html'),
       const textContent   = doc.documentElement.textContent,

        if ( textContent !== string ) {
            return true;
        }

        return false;
    }

}
```

This is the test file:
```
const fs         = require('fs');
const path     = require('path');
const Helper = require('./Helper');

describe('Check for XSS', () => {
 
    it('should return true if string contains malicious code', async () => {
      const vectorPath = path.resolve(__dirname, '../src', 'vector');
      const vectors    = fs.readFileSync(`${vectorPath}/vectors.txt`).toString().split('\n');

      for (const vector of vectors) {
        expect(Helper.checkForXSS(vector)).toBe(true);
      }
    });
  
});
```

Im getting a bunch of these in the console:

```
tcp stream {
  fd: 20,
  readable: true,
  writable: true,
  address: {},
  serverAddr: null
}

child process stdin stream handle leaked at one of: 
    at fakeSpawn (/home/project1/node_modules/leaked-handles/stacks.js:46:21)
    at MongoInstance._launchMongod (/home/project1/node_modules/@shelf/jest-mongodb/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:238:56)
    at MongoInstance.<anonymous> (/home/project1/node_modules/@shelf/jest-mongodb/node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:159:39)
    at fulfilled (/home/project1/node_modules/tslib/tslib.js:166:62)
child process stdin stream handle { fd: 21, readable: false, writable: true }
```

What could be the reason and how can I fix it? 

Please note that if I run all the tests in the app, then I get these memory leaks. If I run those tests in question in isolation, then I dont get them. I also dont get them if I run all the other tests. Also note that all tests pass.

I have been looking for a solution for a while now. This post was the last resort and I hope I'll get a solution here.

**Comment by domenic** [comment]
Closing as modern jsdom and Node.js versions have had substantial memory improvements, and the original repro here is not minimal enough to turn into a worthwhile debugging session for the jsdom maintainers.
