### ISSUE TITLE
Facing test issue for the jsdom:24.0.0 on PPC64LE architecture

### ISSUE THREAD

**Issue by vinodk99** [jsdom/jsdom#3665]
### Basic info:

- **Node.js version:** v18.19.0
- **jsdom version:** 24.0.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
  ... your options here ...
};
const dom = new JSDOM(`
  ... your HTML here ...
`, options);

... Facing below test issue on PPC64LE ...
`  npm run test -- --retries 1

> jsdom@23.2.0 pretest
> npm run prepare && npm run init-wpt


> jsdom@23.2.0 prepare
> npm run convert-idl && npm run generate-js-globals


> jsdom@23.2.0 convert-idl
> node ./scripts/webidl/convert.js


> jsdom@23.2.0 generate-js-globals
> node ./scripts/generate-js-globals.js


> jsdom@23.2.0 init-wpt
> git submodule update --init --recursive

Submodule 'test/web-platform-tests/tests' (https://github.com/web-platform-tests/wpt.git) registered for path 'test/web-platform-tests/tests'
Cloning into '/jsdom/test/web-platform-tests/tests'...
Submodule path 'test/web-platform-tests/tests': checked out '8082bfb906829f64853167c9fc2ef58b3cb1fd75'

> jsdom@23.2.0 test
> mocha test/index.js --retries 1


Error: ENOENT: no such file or directory, open '/jsdom/test/web-platform-tests/tuwpt-manifest.json'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at exports.readManifest (/jsdom/test/web-platform-tests/wpt-manifest-utils.js:42:29)
    at Object.<anonymous> (/jsdom/test/web-platform-tests/run-tuwpts.js:19:18)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/jsdom/test/index.js:64:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:202:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:429:15)
    at async formattedImport (/jsdom/node_modules/mocha/lib/nodejs/esm-utils.js:9:14)
    at async exports.requireOrImport (/jsdom/node_modules/mocha/lib/nodejs/esm-utils.js:42:28)
    at async exports.loadFilesAsync (/jsdom/node_modules/mocha/lib/nodejs/esm-utils.js:100:20)
    at async singleRun (/jsdom/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async exports.handler (/jsdom/node_modules/mocha/lib/cli/run.js:370:5)
`

**Comment by vinodk99** [comment]
Facing above issue on x86 and PPC64LE vm's

**Comment by bmm6o** [comment]
I was able to get past this with `cat wpt-manifest.json > tuwpt-manifest.json`. I don't have tests running yet but I think it's due to other problems.

**Comment by domenic** [comment]
I don't own a PPC64LE computer, so I won't be able to help with this.
