### ISSUE TITLE
Stop polyfilling existing globals

### ISSUE THREAD

**Issue by kettanaito** [jsdom/jsdom#3682]
### Basic info:

- **Node.js version:** v18+
- **jsdom version:** any JSDOM version

### Issue

JSDOM is polyfilling a bunch of already existing global APIs, which leads to all sorts of issues when the underlying code expects those APIs to be actual. 

#### Example 1: `AbortSignal` doesn't extend `EventTarget`

- See https://github.com/nodejs/undici/pull/1910#issuecomment-1464495619

```js
import { implementation as AbortSignal } from 'jsdom/lib/jsdom/living/aborting/AbortSignal-impl'

it('AbortSignal extends EventTarget', () => {
  expect(AbortSignal instanceof EventTarget).toBe(true)
})
```

Root cause: JSDOM extends its own `EventTarget` implementation. This is incorrect and harmful. No child classes of the custom `EventTargetImpl` in JSDOM will be treated as valid events in Node.js. It will throw right here, among other places:

- https://github.com/nodejs/node/blob/544cfc5ef151bca8d625fbccc581200a77b00bc0/lib/events.js#L943

#### Example 2: Custom `Event`

JSDOM implements a custom `EventImpl` instead of relying on the global `Event` class. No derives events will be considered valid events by Node.js.

Example: try dispatching an `Event` on an `EventTarget` instance.

```js
import { implementation as AbortSignal } from 'jsdom/lib/jsdom/living/events/Event-impl'
// Valid global EventTarget in Node.js
const target = new EventTarget()

target.dispatchEvent()
```

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
  ... your options here ...
};
const dom = new JSDOM(`
  ... your HTML here ...
`, options);

... your code that reproduces the problem here, probably using dom.window ...
```

### How does similar code behave in browsers?

Both browsers and Node.js correctly rely on and execute global functions. I expect JSDOM not to rob me of those either.

**Comment by kettanaito** [comment]
Please consider removing custom implementations of things that already exist in Node.js. Those are harmful, and they are already causing real issues, and will cause more and more issues as Node.js aims to align itself with the browser APIs. 

Instead, properly rely on the globals that implement the same specification in both the browser and Node.js. That includes `Event` and `EventTarget` just as two specific examples. This has to be adopted globally to prevent runtime incompatibilities, which are plentiful with JSDOM.

**Comment by domenic** [comment]
You seem to have misunderstood the purpose of the jsdom project.

**Comment by kettanaito** [comment]
@domenic, apologies if that's the case. I just see little value in polyfilling global APIs that exist in both the browser and Node.js. If only those polyfills weren't harmful in practice, wasting quite a bit of time on things that mustn't require time at all.

**Comment by lennerd** [comment]
So JSdom really has no way to disable some of the polyfills to use the ones in Node? This makes some tests very difficualt or even impossible to write.

**Comment by victorhahncastell** [comment]
I agree with the reporter that this behaviour is unexpected and makes life hell in testing -- which is obviously a major use case of JSDOM and usually performed using NodeJS.

The fact that JSDOM's Buffers are neither compatible with NodeJS' nor even based on Uint8Array basically means I need to introduce extra code just to ensure that JSDOM's strange Buffers never sneak into my objects.

**Comment by badams-atlas** [comment]
Hey @kettanaito 

How did you work a round this issue? I'm running into a similar problem.

`TypeError: The "event" argument must be an instance of Event. Received an instance of MessageEvent`

**Comment by schwartzadev** [comment]
I had the same error

**Comment by schwartzadev** [comment]
> How did you work a round this issue? I'm running into a similar problem.
> 
> `TypeError: The "event" argument must be an instance of Event. Received an instance of MessageEvent`
> 
> Note: I'm using vitest rather than jest.

Are there any updates here? I'm seeing the same issue upon updating from node v18 to v22 and it looks like we're stuck on node v22.2.0 because of this issue.

**Comment by diego-aquino** [comment]
> Are there any updates here? I'm seeing the same issue upon updating from node v18 to v22 and it looks like we're stuck on node v22.2.0 because of this issue.
> 
> Edit: we're also using vitest

@schwartzadev, I was stuck on this error as well and I ended up creating a `BroadcastChannel` mock to use in our tests, as I found no other solution.

This is the implementation I made (it runs in our [vitest setup files](https://vitest.dev/config/#setupfiles)). By no means this is a complete `BroadcastChannel`, but it meets our current test requirements. Extend at will.

<details>
<summary><code>tests/setup.ts</code></summary>

```ts
type BroadcastChannelListener = (event: MessageEvent<unknown>) => void

interface BroadcastChannelListenerWithChannel {
  channel: BroadcastChannelMock
  listener: BroadcastChannelListener
}

type BroadcastChannelListenersByType = Map<string, Set<BroadcastChannelListenerWithChannel>>

export class BroadcastChannelMock {
  private static listenersByNameAndType = new Map<string, BroadcastChannelListenersByType>()

  private isActive = true

  constructor(private name: string) {}

  private get listenersByType() {
    const listenersByType =
      BroadcastChannelMock.listenersByNameAndType.get(this.name) ??
      new Map<string, Set<BroadcastChannelListenerWithChannel>>()

    BroadcastChannelMock.listenersByNameAndType.set(this.name, listenersByType)

    return listenersByType
  }

  postMessage(data: unknown) {
    for (const [type, listeners] of this.listenersByType.entries()) {
      for (const { channel, listener } of listeners) {
        if (channel === this || !channel.isActive) {
          continue
        }

        const event = new MessageEvent(type, { data })
        listener(event)
      }
    }
  }

  addEventListener(event: string, listener: BroadcastChannelListener) {
    const listeners = this.listenersByType.get(event) ?? new Set()
    this.listenersByType.set(event, listeners)

    listeners.add({ channel: this, listener })
  }

  removeEventListener(event: string, listener: BroadcastChannelListener) {
    const listeners = this.listenersByType.get(event)

    for (const listenerWithChannel of listeners ?? []) {
      if (listenerWithChannel.listener === listener) {
        listeners?.delete(listenerWithChannel)
      }
    }
  }

  close() {
    this.isActive = false
  }

  static clear() {
    for (const listenersByType of this.listenersByNameAndType.values()) {
      for (const listeners of listenersByType.values()) {
        listeners.clear()
      }
      listenersByType.clear()
    }

    this.listenersByNameAndType.clear()
  }
}

globalThis.BroadcastChannel = BroadcastChannelMock as unknown as typeof BroadcastChannel

afterEach(() => {
  BroadcastChannelMock.clear()
})
```

</details>

**Comment by AndrewBogdanovTSS** [comment]
Can this issue be reopened as proper solution is not yet available?

**Comment by MarcMcIntosh** [comment]
Updated to node v24 and started getting this error
```
In the case of an unhandled error, no tags will be "provided" or "invalidated". TypeError: RequestInit: Expected signal ("AbortSignal {}") to be an instance of AbortSignal.
    at Object.webidl.errors.exception (node:internal/deps/undici/undici:4096:14)
    at Object.AbortSignal (node:internal/deps/undici/undici:4338:31)
    at node:internal/deps/undici/undici:10747:41
    at node:internal/deps/undici/undici:4389:16
    at Object.RequestInit (node:internal/deps/undici/undici:4371:21)
    at new Request (node:internal/deps/undici/undici:10111:34)
    at Object.construct (file:///home/runner/work/refact/refact/refact-agent/gui/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/utils/recordRawHeaders.ts:185:33)
    at file:///home/runner/work/refact/refact/refact-agent/gui/node_modules/@reduxjs/toolkit/src/query/fetchBaseQuery.ts:224:21
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at Object.queryFn (/home/runner/work/refact/refact/refact-agent/gui/src/services/refact/ping.ts:15:26)
```

**Comment by Finesse** [comment]
This is what I have to do to prevent JSDOM from overwriting some APIs:

```js
// init.js — the file set in `setupFilesAfterEnv` of `jest.config.js`

import { webcrypto as crypto } from 'node:crypto';
import { CompressionStream, DecompressionStream } from 'node:stream/web';
import { TextDecoder, TextEncoder } from 'node:util';

// These APIs are available in the Node.js global scope, but JSDOM removes or breaks them, so we need to retrieve them
Object.assign(global, {
  TextEncoder,
  TextDecoder,
  CompressionStream,
  DecompressionStream,
  // eslint-disable-next-line global-require
  Uint8Array: Object.getPrototypeOf(Object.getPrototypeOf(require('node:buffer').Buffer.from(''))).constructor, // The JSDOM's implementation isn't compatible with 'node:crypto'
});
Object.defineProperty(global, 'crypto', {
  value: crypto,
  configurable: true,
});
```

**Comment by domenic** [comment]
To be clear, jsdom does not override or touch any globals. You may be using some sort of third-party library or test framework which does that, but our code has nothing to do with that.

**Comment by Finesse** [comment]
> To be clear, jsdom does not override or touch any globals. You may be using some sort of third-party library or test framework which does that, but our code has nothing to do with that.

I [use](https://github.com/mytonwalletorg/mytonwallet/blob/26225c8b6de1c7a0c4d9081f59fd955aedfc88ec/jest.config.js#L14) Jest with JSDOM. As soon as I remove `testEnvironment: 'jest-environment-jsdom'`, the API problems disappear. It happens because Jest [replaces](https://github.com/jestjs/jest/blob/546362157367a160664226a7cc0fa1646759cf8f/packages/jest-environment-jsdom-abstract/src/index.ts#L78) all global variable with what JSDOM returns.

As far as I understand the goal of JSDOM is reproducing the browser global variable in Node.js environment. All the above APIs (`TextEncoder`, `CompressionStream`, `crypto`, etc) are available both in Node.js and browser, so JSDOM should include the Node.js's counterparts into the reproduced environment.

**Comment by domenic** [comment]
> I [use](https://github.com/mytonwalletorg/mytonwallet/blob/26225c8b6de1c7a0c4d9081f59fd955aedfc88ec/jest.config.js#L14) Jest with JSDOM.

Got it. So as I said, this is a problem with a third-party package, and not one that we can support. You should ask Jest to stop doing that.

> so JSDOM should include the Node.js's counterparts into the reproduced environment.

This does not follow. Node.js's counterparts are their own implementations, which are not compatible with the jsdom global environment.
