### ISSUE TITLE
TypeError when parsing `<constructor>` element

### ISSUE THREAD

**Issue by daniellockyer** [jsdom/jsdom#3709]
### Basic info:

- **Node.js version:** v18
- **jsdom version:** 23 & 24

### General

We use jsdom within [Ghost](https://github.com/tryghost/ghost) and noticed that some inputs are erroring out within jsdom. After investigation, it seems to be due to the use of `<constructor>` within the body.

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

let dom = new JSDOM(`<constructor>`);
```

I get this stack trace:
```
..../node_modules/jsdom/lib/jsdom/living/helpers/create-element.js:277
    result = elementInterface.createImpl(_globalObject, [], {
                              ^

TypeError: Cannot read properties of undefined (reading 'createImpl')
    at createElement (..../node_modules/jsdom/lib/jsdom/living/helpers/create-element.js:277:31)
    at JSDOMParse5Adapter.createElement (..../node_modules/jsdom/lib/jsdom/browser/parser/html.js:78:21)
    at Parser._insertElement (..../node_modules/parse5/dist/cjs/parser/index.js:267:42)
    at genericStartTagInBody (..../node_modules/parse5/dist/cjs/parser/index.js:1854:7)
    at startTagInBody (..../node_modules/parse5/dist/cjs/parser/index.js:2068:13)
    at Parser._startTagOutsideForeignContent (..../node_modules/parse5/dist/cjs/parser/index.js:823:17)
    at Parser._processStartTag (..../node_modules/parse5/dist/cjs/parser/index.js:793:18)
    at Parser.onStartTag (..../node_modules/parse5/dist/cjs/parser/index.js:773:14)
    at Tokenizer.emitCurrentTagToken (..../node_modules/parse5/dist/cjs/tokenizer/index.js:393:26)
    at Tokenizer._stateTagName (..../node_modules/parse5/dist/cjs/tokenizer/index.js:1084:22)

Node.js v18.20.2
```

Whereas using an element of a different name, `<abc>`, works.

### How does similar code behave in browsers?

I would expect the code not to crash on this element 🙂

**Comment by daniellockyer** [comment]
@domenic Nice, thanks!
