### ISSUE TITLE
Astro SSR [Node built-in issue]

### ISSUE THREAD

**Issue by Mukul1127** [jsdom/jsdom#3753]
### Basic info:

- **Node.js version:** v22.5.1 
- **jsdom version:** 24.1.1 

### Minimal reproduction case

Try to use JSDOM with Astro SSR. Fails due to JSDOM using node built-ins without `node:` prefix.

Error:
```
18:46:02 [build] Building hybrid entrypoints...
18:46:02 [ERROR] [vite] x Build failed in 733ms
[commonjs--resolver] [plugin vite:resolve] Cannot bundle Node.js built-in "path" imported from "node_modules/.pnpm/jsdom@24.1.1/node_modules/jsdom/lib/api.js". Consider disabling ssr.noExternal or remove the built-in dependency.
file: /home/mukul/TestProject/node_modules/.pnpm/jsdom@24.1.1/node_modules/jsdom/lib/api.js
  Stack trace:
    at getRollupError (file:///home/mukul/TestProject/node_modules/.pnpm/rollup@4.19.1/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at Object.error (file:///home/mukul/TestProject/node_modules/.pnpm/rollup@4.19.1/node_modules/rollup/dist/es/shared/node-entry.js:19681:20)
    at Object.handler (file:///home/mukul/TestProject/node_modules/.pnpm/vite@5.3.5_@types+node@22.0.0_lightningcss@1.25.1_terser@5.31.3/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:65329:15)
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/mukul/TestProject/node_modules/.pnpm/rollup@4.19.1/node_modules/rollup/dist/es/shared/node-entry.js:19766:28)
    at async ModuleLoader.resolveId (file:///home/mukul/TestProject/node_modules/.pnpm/rollup@4.19.1/node_modules/rollup/dist/es/shared/node-entry.js:18850:15)
 ELIFECYCLE  Command failed with exit code 1.
```

Doc: https://docs.astro.build/en/guides/imports/#node-builtins

### How does similar code behave in browsers?

N/A since it's a build error, development server works fine

**Comment by Mukul1127** [comment]
Closing this as it seems to be caused by me using cloudflare ssr which doesn't support nodejs built-ins. Though the error was not helpful.

**Comment by Mukul1127** [comment]
Actually it would work with cloudflare only when built-ins are prefixed with `node:` as it says here: https://developers.cloudflare.com/workers/runtime-apis/nodejs/

**Comment by domenic** [comment]
This module is made for use with Node.js, as it says in the first sentence of the readme.

**Comment by Mukul1127** [comment]
> This module is made for use with Node.js, as it says in the first sentence of the readme.

Yes I understand that, I probably could have been more clear but I was basically asking would you consider using for example: `node:path` instead of `path` to add compatibility with Astro.

**Comment by domenic** [comment]
No; if there are other runtimes which have imperfect compatibility with Node.js, then you should file bugs on them to improve their compatibility. We do not have the resources to support them in jsdom.

**Comment by Mukul1127** [comment]
> No; if there are other runtimes which have imperfect compatibility with Node.js, then you should file bugs on them to improve their compatibility. We do not have the resources to support them in jsdom.

It's not imperfect compatibility, but node's recommendation. I'll research what can be done on cloudflare's end and Astro.

**Comment by Mukul1127** [comment]
Update: the fix is hidden away but it's possible: https://docs.astro.build/en/guides/integrations-guide/cloudflare/#nodejs-compatibility, works when using nodejs_compat_v2 and using plain "Buffer"
