### ISSUE TITLE
rrweb-cssom 0.8.0 now supports `@layers`

### ISSUE THREAD

**Issue by Exac** [jsdom/jsdom#3785]
Hi, I noticed that https://github.com/rrweb-io/CSSOM/pull/5 was just merged, so we could upgrade to `rrweb-cssom@0.8.0`.

Examples of issues that this could help resolve:
- https://github.com/jsdom/jsdom/issues/2177#issuecomment-1724971596
- https://github.com/primefaces/primeng/issues/14085
- https://github.com/thymikee/jest-preset-angular/issues/2194

### Basic info:

- **Node.js version:** v20.17.0
- **jsdom version:** v22.0.0

### Minimal reproduction case

https://stackblitz.com/edit/jsdom-rrweb-cssom-0-7-1-errors?file=index.js

```js
const jsdom = require('jsdom');
const { JSDOM } = jsdom;

const dom = new JSDOM(`
<!DOCTYPE html>
<html>
<head>
  <style>
    @layer foo, bar;

    @layer foo {
      p {
        color: yellow;
      }
    }
    
    @layer bar {
      p {
        background-color: black;
      }
    }

    p {
      font-size: 4rem;
    }
  </style>
</head>
<body>
  <p>hello, jsdom</p>
</body>
</html>
`);

const pEl = dom.window.document.querySelector('p');
const { color, backgroundColor, fontSize } = dom.window.getComputedStyle(pEl);

console.log({ color, backgroundColor, fontSize });
```
```text
Error: Could not parse CSS stylesheet
    at exports.createStylesheet (/home/projects/jsdom-rrweb-cssom-0-7-1-errors/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:37:21)
    at HTMLStyleElementImpl._updateAStyleBlock (/home/projects/jsdom-rrweb-cssom-0-7-1-errors/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:68:5)
    at HTMLStyleElementImpl._poppedOffStackOfOpenElements (/home/projects/jsdom-rrweb-cssom-0-7-1-errors/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:42:10)
    at JSDOMParse5Adapter.onItemPop (/home/projects/jsdom-rrweb-cssom-0-7-1-errors/node_modules/jsdom/lib/jsdom/browser/parser/html.js:175:43)
    at Parser.onItemPop (/home/projects/jsdom-rrweb-cssom-0-7-1-errors/node_modules/parse5/dist/cjs/parser/index.js:176:90)
    at OpenElementStack.pop (/home/projects/jsdom-rrweb-cssom-0-7-1-errors/node_modules/parse5/dist/cjs/parser/open-element-stack.js:83:22)
    at endTagInText (/home/projects/jsdom-rrweb-cssom-0-7-1-errors/node_modules/parse5/dist/cjs/parser/index.js:2349:20)
    at Parser._endTagOutsideForeignContent (/home/projects/jsdom-rrweb-cssom-0-7-1-errors/node_modules/parse5/dist/cjs/parser/index.js:988:17)
    at Parser.onEndTag (/home/projects/jsdom-rrweb-cssom-0-7-1-errors/node_modules/parse5/dist/cjs/parser/index.js:953:18)
    at Tokenizer.emitCurrentTagToken (/home/projects/jsdom-rrweb-cssom-0-7-1-errors/node_modules/parse5/dist/cjs/tokenizer/index.js:385:26) 
    @layer foo, bar;

    @layer foo {
      p {
        color: yellow;
      }
    }
    
    @layer bar {
      p {
        background-color: black;
      }
    }

    p {
      font-size: 4rem;
    }
  
{ color: '', backgroundColor: 'rgba(0, 0, 0, 0)', fontSize: '' }
```

### How does similar code behave in browsers?
https://stackblitz.com/edit/jsdom-example-of-css-layers
![image](https://github.com/user-attachments/assets/766e1b93-9cec-454c-bb71-e6f502cf835e)

**Comment by domenic** [comment]
This will be fixed by https://github.com/jsdom/jsdom/pull/3811, but no test coverage for `@layer` was added in that PR, so I will leave this issue open with an appropriate label before we can close it.

**Comment by domenic** [comment]
This is still not working. `getComputedStyle(pEl).color` returns `""`, not the correct `rgb(255, 255, 0)` as expected.

I'll be committing a failing test to help confirm this.

**Comment by centigrade-julian-lang** [comment]
Are there any updates? Is it roughly known when we can expect a solution?

**Comment by domenic** [comment]
https://x.com/slicknet/status/782274190451671040

**Comment by centigrade-julian-lang** [comment]
Thanks for replying. The real question was the second part though - this issue shows, that there was a bit of work done, but not completed. Are there any plans to continue working on this soon? Or is there a roadmap clarifying when css-layers are planned to arrive?

**Comment by domenic** [comment]
There are no such plans, unless you are volunteering.
