### ISSUE TITLE
Code should stop running after window.close.

### ISSUE THREAD

**Issue by tolmasky** [jsdom/jsdom#955]
If window.close() is called from anywhere, any execution should just stop (just like the browser). Currently it puts you in a really weird state. Here is an example:

``` javascript
    var jsdom = require("jsdom");

    jsdom.env({
        html: "<html><body></body></html>",
        src: ["setTimeout(function() { window.close(); console.log(document); }, 1000);"],
        created: function(errors, window)
        {
            window.console = console;
        }
    });
```

This throws:
ReferenceError: document is not defined
    at null.&lt;anonymous&gt; (/test.js:undefined:undefined&lt;script&gt;:1:53)
    at Timer.listOnTimeout [as ontimeout](timers.js:112:15)

Even worse during initial load:

``` javascript
    var jsdom = require("jsdom");

    jsdom.env({
        html: "<html><body></body></html>",
        src: ["window.close(); console.log(document);"],
        created: function(errors, window)
        {
            window.console = console;
        }
    });
```

```
  window.document.documentElement.removeChild(script);
                 ^
```

TypeError: Cannot read property 'documentElement' of undefined
    at jsdom.js:311:22
    at Array.forEach (native)
    at processHTML (jsdom.js:304:16)
    at Object.exports.env.exports.jsdom.env (jsdom.js:142:5)
    at Object.<anonymous> (/Users/tolmasky/Desktop/test.js:11:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

The actual example I ran into though, was use .run (which I imagine will be harder to catch, but still fundamentally the same issue):

``` javascript
    var jsdom = require("jsdom");

    jsdom.env({
        html: "<html><body></body></html>",
        created: function(errors, window)
        {
            window.console = console;
        },
        done: function(errors, window)
        {
            window.run("window.close(); console.log(document)");
        }
    });
```

**Comment by PhilippMi** [comment]
Is there any progress on this issue?

**Comment by domenic** [comment]
No.
